import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// Client-oriented build on purpose: the same bundle drops into Capacitor later
// without a server-rendering layer to unpick first.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.svg', 'apple-touch-icon.png'],
      manifest: {
        name: 'What a Pull',
        short_name: 'What a Pull',
        description: 'Pull something worth keeping.',
        theme_color: '#14120E',
        background_color: '#F4F1EA',
        display: 'standalone',
        start_url: '/',
        // Generated by scripts/gen-icons.mjs. A separate maskable entry matters: without
        // one, a launcher that crops to a circle takes the bite out of the mark itself.
        icons: [
          { src: '/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        globPatterns: ['**/*.{js,css,html,svg,png,woff2}'],
        navigateFallback: '/index.html',
      },
    }),
  ],
  server: { port: 5173, host: '127.0.0.1' },
  /*
   * No production sourcemap.
   *
   * It was 2.5MB beside a 557KB bundle — five times the app, published on a CDN and
   * counted against the deploy on every build. The code is AGPL-3.0 and readable on GitHub,
   * so this was never protecting anything; it was simply the largest file in the
   * deployment, serving a debugger nobody attaches to production.
   *
   * `hidden` rather than `false` would keep the file for a symbol uploader if error
   * reporting is ever added, and adding error reporting is a privacy policy change
   * first (see `components/ErrorBoundary.tsx`), so it can be turned back on then.
   */
  build: { target: 'es2022', sourcemap: false },
  test: {
    environment: 'node',
    /*
     * Not UTC, on purpose.
     *
     * `history_events.occurred_on` is a UTC calendar day, and the History screen
     * labels it "Today"/"Yesterday". The first version compared it against *local*
     * midnight, which is wrong for every reader whose date differs from UTC's — and
     * a suite running in UTC cannot fail on it, because there local and UTC agree.
     * The bug shipped and was found in review rather than by these tests.
     *
     * Brisbane is UTC+10 with no daylight saving, so it is reliably offset without
     * being seasonally ambiguous. Anything that only passes at UTC is a timezone
     * assumption, and this is how it gets caught here instead of by a reader.
     */
    env: { TZ: 'Australia/Brisbane' },
    include: ['src/**/*.test.{ts,tsx}'],
    exclude: ['**/node_modules/**', '**/dist/**'],
    passWithNoTests: true,
  },
});
