import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import jsxA11y from 'eslint-plugin-jsx-a11y';

export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/build/**',
      '**/.turbo/**',
      '**/coverage/**',
      '**/node_modules/**',
      'packages/db/src/database.types.ts',
      'packages/prompts/baml_client/**', // generated by `pnpm baml:generate`
      'supabase/functions/**', // Deno runtime, separate lint pass
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always'],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },
  {
    // The Archive design law is partly enforceable by lint: accessibility is
    // not optional here, so a11y rules are errors rather than warnings.
    files: ['**/*.tsx'],
    plugins: { 'react-hooks': reactHooks, 'jsx-a11y': jsxA11y },
    rules: {
      ...reactHooks.configs.recommended.rules,
      ...jsxA11y.flatConfigs.recommended.rules,

      /*
       * One addition to the rule's allowed roles, and it is an accessibility
       * fix rather than an exemption from one.
       *
       * A container with `overflow-x: auto` must be focusable, or a keyboard
       * user cannot scroll it and everything past its right edge is simply
       * unreachable — WCAG 2.1.1, and what axe reports as
       * `scrollable-region-focusable`. The remedy is a `region` with a name and
       * `tabindex="0"`, which is precisely what this rule's default role list
       * happens not to include. Adding it lets the correct markup pass; a bare
       * focusable div still does not.
       */
      'jsx-a11y/no-noninteractive-tabindex': ['error', { roles: ['tabpanel', 'region'] }],
    },
  },
);
