/**
 * Provider interfaces.
 *
 * Selected by environment so a self-hosted instance is never forced to
 * reproduce our vendors. Round 1 ships only the stub implementations: the
 * step-machine is wired and testable end to end without any API key, and
 * round 2 swaps in real providers without touching the pipeline.
 */

export interface SummaryInput {
  workTitle: string;
  kind: string;
  context: string;
}

export interface CanonicalSummary {
  title: string;
  elevatorPitch: string;
  whyItMatters: string;
  pulls: { headline: string; body: string; whyItMatters: string }[];
}

export interface Usage {
  inputTokens: number;
  outputTokens: number;
  costCents: number;
}

export interface SummaryProvider {
  readonly name: string;
  /**
   * `model` is returned rather than read off the provider because a provider may fall
   * back between models mid-run — the newest Flash returns 503 under load often enough
   * that a pipeline pinned to it stalls. `job_steps.model` has to name the model that
   * actually produced this summary, or provenance is fiction.
   */
  generateSummary(
    input: SummaryInput,
  ): Promise<{ summary: CanonicalSummary; usage: Usage; model: string }>;
}

export interface EmbeddingProvider {
  readonly name: string;
  embed(texts: string[]): Promise<{ vectors: number[][]; usage: Usage }>;
}

export interface ImageProvider {
  readonly name: string;
  generateArtwork(prompt: string): Promise<{ path: string; usage: Usage } | null>;
}

/** Deterministic, free, and offline. Enough to exercise every step. */
export const stubSummaryProvider: SummaryProvider = {
  name: 'stub',
  async generateSummary(input) {
    return {
      summary: {
        title: input.workTitle,
        elevatorPitch: `A stub summary of ${input.workTitle}.`,
        whyItMatters: 'Generated by the stub provider; replaced in round 2.',
        pulls: [],
      },
      usage: { inputTokens: 0, outputTokens: 0, costCents: 0 },
      model: 'stub',
    };
  },
};

export const stubEmbeddingProvider: EmbeddingProvider = {
  name: 'stub',
  async embed(texts) {
    return {
      vectors: texts.map(() => new Array(1536).fill(0)),
      usage: { inputTokens: 0, outputTokens: 0, costCents: 0 },
    };
  },
};

/**
 * Artwork is the first thing to switch off under cost pressure: an illustration
 * can cost several times the text generation it accompanies. Returning null is
 * a supported outcome, not a failure — the product degrades to typography.
 */
export const disabledImageProvider: ImageProvider = {
  name: 'disabled',
  async generateArtwork() {
    return null;
  },
};
