// Generated by `pnpm db:types` from the Supabase schema.
// Do not edit by hand — CI check 4 fails if this file is stale.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      artworks: {
        Row: {
          alt_text: string
          cost_cents: number
          created_at: string
          id: string
          model: string | null
          prompt: string | null
          scope: string
          storage_path: string
          summary_id: string
        }
        Insert: {
          alt_text?: string
          cost_cents?: number
          created_at?: string
          id?: string
          model?: string | null
          prompt?: string | null
          scope?: string
          storage_path: string
          summary_id: string
        }
        Update: {
          alt_text?: string
          cost_cents?: number
          created_at?: string
          id?: string
          model?: string | null
          prompt?: string | null
          scope?: string
          storage_path?: string
          summary_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "artworks_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
        ]
      }
      citation_anchors: {
        Row: {
          confidence: number
          created_at: string
          edition_id: string | null
          id: string
          locator: string
          locator_type: Database["public"]["Enums"]["locator_type"]
          note: string | null
          pull_id: string
          quote: string | null
        }
        Insert: {
          confidence?: number
          created_at?: string
          edition_id?: string | null
          id?: string
          locator: string
          locator_type: Database["public"]["Enums"]["locator_type"]
          note?: string | null
          pull_id: string
          quote?: string | null
        }
        Update: {
          confidence?: number
          created_at?: string
          edition_id?: string | null
          id?: string
          locator?: string
          locator_type?: Database["public"]["Enums"]["locator_type"]
          note?: string | null
          pull_id?: string
          quote?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "citation_anchors_edition_id_fkey"
            columns: ["edition_id"]
            isOneToOne: false
            referencedRelation: "editions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "citation_anchors_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      contributors: {
        Row: {
          bio: string | null
          created_at: string
          id: string
          name: string
          slug: string
        }
        Insert: {
          bio?: string | null
          created_at?: string
          id?: string
          name: string
          slug: string
        }
        Update: {
          bio?: string | null
          created_at?: string
          id?: string
          name?: string
          slug?: string
        }
        Relationships: []
      }
      convictions: {
        Row: {
          confidence: number
          created_at: string
          id: string
          pull_id: string
          rationale: string | null
          stance: Database["public"]["Enums"]["stance"]
          superseded_by: string | null
          user_id: string
        }
        Insert: {
          confidence?: number
          created_at?: string
          id?: string
          pull_id: string
          rationale?: string | null
          stance: Database["public"]["Enums"]["stance"]
          superseded_by?: string | null
          user_id: string
        }
        Update: {
          confidence?: number
          created_at?: string
          id?: string
          pull_id?: string
          rationale?: string | null
          stance?: Database["public"]["Enums"]["stance"]
          superseded_by?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "convictions_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "convictions_superseded_by_fkey"
            columns: ["superseded_by"]
            isOneToOne: false
            referencedRelation: "convictions"
            referencedColumns: ["id"]
          },
        ]
      }
      cost_ledger: {
        Row: {
          cost_cents: number
          created_at: string
          id: number
          job_id: string | null
          operation: string
          provider: string
          quantity: number
          step_id: string | null
          unit: string
        }
        Insert: {
          cost_cents: number
          created_at?: string
          id?: never
          job_id?: string | null
          operation: string
          provider: string
          quantity: number
          step_id?: string | null
          unit: string
        }
        Update: {
          cost_cents?: number
          created_at?: string
          id?: never
          job_id?: string | null
          operation?: string
          provider?: string
          quantity?: number
          step_id?: string | null
          unit?: string
        }
        Relationships: [
          {
            foreignKeyName: "cost_ledger_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "generation_jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cost_ledger_step_id_fkey"
            columns: ["step_id"]
            isOneToOne: false
            referencedRelation: "job_steps"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_pulls: {
        Row: {
          blurb: string | null
          created_at: string
          curator: Database["public"]["Enums"]["curator_kind"]
          day: string
          ordinal: number
          pull_id: string
        }
        Insert: {
          blurb?: string | null
          created_at?: string
          curator?: Database["public"]["Enums"]["curator_kind"]
          day: string
          ordinal: number
          pull_id: string
        }
        Update: {
          blurb?: string | null
          created_at?: string
          curator?: Database["public"]["Enums"]["curator_kind"]
          day?: string
          ordinal?: number
          pull_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "daily_pulls_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      editions: {
        Row: {
          created_at: string
          duration_seconds: number | null
          id: string
          is_primary: boolean
          isbn13: string | null
          label: string
          language: string
          page_count: number | null
          publisher: string | null
          url: string | null
          work_id: string
          year: number | null
        }
        Insert: {
          created_at?: string
          duration_seconds?: number | null
          id?: string
          is_primary?: boolean
          isbn13?: string | null
          label: string
          language?: string
          page_count?: number | null
          publisher?: string | null
          url?: string | null
          work_id: string
          year?: number | null
        }
        Update: {
          created_at?: string
          duration_seconds?: number | null
          id?: string
          is_primary?: boolean
          isbn13?: string | null
          label?: string
          language?: string
          page_count?: number | null
          publisher?: string | null
          url?: string | null
          work_id?: string
          year?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "editions_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      explanations: {
        Row: {
          audio_path: string | null
          client_mutation_id: string | null
          created_at: string
          gap_score: number | null
          graded_at: string | null
          id: string
          missed_points: Json
          pull_id: string
          text: string
          user_id: string
        }
        Insert: {
          audio_path?: string | null
          client_mutation_id?: string | null
          created_at?: string
          gap_score?: number | null
          graded_at?: string | null
          id?: string
          missed_points?: Json
          pull_id: string
          text: string
          user_id: string
        }
        Update: {
          audio_path?: string | null
          client_mutation_id?: string | null
          created_at?: string
          gap_score?: number | null
          graded_at?: string | null
          id?: string
          missed_points?: Json
          pull_id?: string
          text?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "explanations_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_impressions: {
        Row: {
          action: string | null
          id: number
          position: number
          pull_id: string
          recipe_id: string | null
          shown_at: string
          user_id: string
        }
        Insert: {
          action?: string | null
          id?: never
          position?: number
          pull_id: string
          recipe_id?: string | null
          shown_at?: string
          user_id: string
        }
        Update: {
          action?: string | null
          id?: never
          position?: number
          pull_id?: string
          recipe_id?: string | null
          shown_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_impressions_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "feed_impressions_recipe_id_fkey"
            columns: ["recipe_id"]
            isOneToOne: false
            referencedRelation: "feed_recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      feed_recipes: {
        Row: {
          created_at: string
          forked_from: string | null
          id: string
          is_default: boolean
          is_public: boolean
          name: string
          spec: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          forked_from?: string | null
          id?: string
          is_default?: boolean
          is_public?: boolean
          name: string
          spec?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          forked_from?: string | null
          id?: string
          is_default?: boolean
          is_public?: boolean
          name?: string
          spec?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "feed_recipes_forked_from_fkey"
            columns: ["forked_from"]
            isOneToOne: false
            referencedRelation: "feed_recipes"
            referencedColumns: ["id"]
          },
        ]
      }
      follows: {
        Row: {
          created_at: string
          followee_id: string
          follower_id: string
        }
        Insert: {
          created_at?: string
          followee_id: string
          follower_id: string
        }
        Update: {
          created_at?: string
          followee_id?: string
          follower_id?: string
        }
        Relationships: []
      }
      generation_jobs: {
        Row: {
          attempts: number
          cost_cents: number
          created_at: string
          current_step: string
          error: string | null
          finished_at: string | null
          id: string
          kind: string
          requester_id: string | null
          status: Database["public"]["Enums"]["job_status"]
          summary_id: string | null
          target: Json
          updated_at: string
          visibility: Database["public"]["Enums"]["visibility"]
          work_id: string | null
        }
        Insert: {
          attempts?: number
          cost_cents?: number
          created_at?: string
          current_step?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          kind?: string
          requester_id?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          summary_id?: string | null
          target?: Json
          updated_at?: string
          visibility?: Database["public"]["Enums"]["visibility"]
          work_id?: string | null
        }
        Update: {
          attempts?: number
          cost_cents?: number
          created_at?: string
          current_step?: string
          error?: string | null
          finished_at?: string | null
          id?: string
          kind?: string
          requester_id?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          summary_id?: string | null
          target?: Json
          updated_at?: string
          visibility?: Database["public"]["Enums"]["visibility"]
          work_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "generation_jobs_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "generation_jobs_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      highlights: {
        Row: {
          created_at: string
          end_offset: number
          field: string
          id: string
          pull_id: string
          start_offset: number
          text: string
          user_id: string
        }
        Insert: {
          created_at?: string
          end_offset: number
          field?: string
          id?: string
          pull_id: string
          start_offset: number
          text: string
          user_id: string
        }
        Update: {
          created_at?: string
          end_offset?: number
          field?: string
          id?: string
          pull_id?: string
          start_offset?: number
          text?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "highlights_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      history_events: {
        Row: {
          created_at: string
          dwell_ms: number | null
          id: number
          kind: string
          pull_id: string | null
          summary_id: string | null
          user_id: string
          work_id: string | null
        }
        Insert: {
          created_at?: string
          dwell_ms?: number | null
          id?: never
          kind: string
          pull_id?: string | null
          summary_id?: string | null
          user_id: string
          work_id?: string | null
        }
        Update: {
          created_at?: string
          dwell_ms?: number | null
          id?: never
          kind?: string
          pull_id?: string | null
          summary_id?: string | null
          user_id?: string
          work_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "history_events_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "history_events_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "history_events_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      interleave_config: {
        Row: {
          base_probability: number
          id: boolean
          max_per_session: number
          max_probability: number
          min_gap_cards: number
          pressure_multiplier: number
          updated_at: string
          warmup_cards: number
          weight_conviction: number
          weight_counterpull: number
          weight_delta_probe: number
          weight_recall: number
          weight_say_it_back: number
        }
        Insert: {
          base_probability?: number
          id?: boolean
          max_per_session?: number
          max_probability?: number
          min_gap_cards?: number
          pressure_multiplier?: number
          updated_at?: string
          warmup_cards?: number
          weight_conviction?: number
          weight_counterpull?: number
          weight_delta_probe?: number
          weight_recall?: number
          weight_say_it_back?: number
        }
        Update: {
          base_probability?: number
          id?: boolean
          max_per_session?: number
          max_probability?: number
          min_gap_cards?: number
          pressure_multiplier?: number
          updated_at?: string
          warmup_cards?: number
          weight_conviction?: number
          weight_counterpull?: number
          weight_delta_probe?: number
          weight_recall?: number
          weight_say_it_back?: number
        }
        Relationships: []
      }
      interrupt_events: {
        Row: {
          grade: Database["public"]["Enums"]["recall_grade"] | null
          id: string
          kind: Database["public"]["Enums"]["interrupt_kind"]
          latency_ms: number | null
          pull_id: string
          responded_at: string | null
          response: Database["public"]["Enums"]["interrupt_response"] | null
          session_id: string | null
          shown_at: string
          slot_position: number
          user_id: string
        }
        Insert: {
          grade?: Database["public"]["Enums"]["recall_grade"] | null
          id?: string
          kind: Database["public"]["Enums"]["interrupt_kind"]
          latency_ms?: number | null
          pull_id: string
          responded_at?: string | null
          response?: Database["public"]["Enums"]["interrupt_response"] | null
          session_id?: string | null
          shown_at?: string
          slot_position: number
          user_id: string
        }
        Update: {
          grade?: Database["public"]["Enums"]["recall_grade"] | null
          id?: string
          kind?: Database["public"]["Enums"]["interrupt_kind"]
          latency_ms?: number | null
          pull_id?: string
          responded_at?: string | null
          response?: Database["public"]["Enums"]["interrupt_response"] | null
          session_id?: string | null
          shown_at?: string
          slot_position?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "interrupt_events_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interrupt_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "session_seeds"
            referencedColumns: ["id"]
          },
        ]
      }
      job_steps: {
        Row: {
          attempt: number
          cost_cents: number
          created_at: string
          duration_ms: number | null
          error: string | null
          finished_at: string | null
          id: string
          input_tokens: number | null
          job_id: string
          model: string | null
          output: Json | null
          output_tokens: number | null
          prompt_version: string | null
          status: Database["public"]["Enums"]["job_status"]
          step: string
        }
        Insert: {
          attempt?: number
          cost_cents?: number
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          finished_at?: string | null
          id?: string
          input_tokens?: number | null
          job_id: string
          model?: string | null
          output?: Json | null
          output_tokens?: number | null
          prompt_version?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          step: string
        }
        Update: {
          attempt?: number
          cost_cents?: number
          created_at?: string
          duration_ms?: number | null
          error?: string | null
          finished_at?: string | null
          id?: string
          input_tokens?: number | null
          job_id?: string
          model?: string | null
          output?: Json | null
          output_tokens?: number | null
          prompt_version?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          step?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_steps_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "generation_jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      knowledge_states: {
        Row: {
          acquired_via: Database["public"]["Enums"]["acquisition"]
          difficulty: number
          lapses: number
          last_seen_at: string
          next_due_at: string
          pull_id: string
          reps: number
          stability: number
          user_id: string
        }
        Insert: {
          acquired_via?: Database["public"]["Enums"]["acquisition"]
          difficulty?: number
          lapses?: number
          last_seen_at?: string
          next_due_at?: string
          pull_id: string
          reps?: number
          stability?: number
          user_id: string
        }
        Update: {
          acquired_via?: Database["public"]["Enums"]["acquisition"]
          difficulty?: number
          lapses?: number
          last_seen_at?: string
          next_due_at?: string
          pull_id?: string
          reps?: number
          stability?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "knowledge_states_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      moderation_decisions: {
        Row: {
          action: string
          created_at: string
          id: string
          moderator_id: string | null
          rationale: string | null
          report_id: string | null
        }
        Insert: {
          action: string
          created_at?: string
          id?: string
          moderator_id?: string | null
          rationale?: string | null
          report_id?: string | null
        }
        Update: {
          action?: string
          created_at?: string
          id?: string
          moderator_id?: string | null
          rationale?: string | null
          report_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "moderation_decisions_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "reports"
            referencedColumns: ["id"]
          },
        ]
      }
      notes: {
        Row: {
          body: string
          created_at: string
          id: string
          pull_id: string | null
          summary_id: string | null
          updated_at: string
          user_id: string
          visibility: Database["public"]["Enums"]["visibility"]
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          pull_id?: string | null
          summary_id?: string | null
          updated_at?: string
          user_id: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          pull_id?: string | null
          summary_id?: string | null
          updated_at?: string
          user_id?: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Relationships: [
          {
            foreignKeyName: "notes_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notes_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
        ]
      }
      preference_profiles: {
        Row: {
          counter_rate: number
          created_at: string
          daily_minutes: number
          excluded_topics: string[]
          interrupt_rate: number
          media_kinds: Database["public"]["Enums"]["work_kind"][]
          novelty: number
          onboarded_at: string | null
          spoilers: Database["public"]["Enums"]["spoiler_level"]
          technical_level: number
          topic_weights: Json
          updated_at: string
          user_id: string
        }
        Insert: {
          counter_rate?: number
          created_at?: string
          daily_minutes?: number
          excluded_topics?: string[]
          interrupt_rate?: number
          media_kinds?: Database["public"]["Enums"]["work_kind"][]
          novelty?: number
          onboarded_at?: string | null
          spoilers?: Database["public"]["Enums"]["spoiler_level"]
          technical_level?: number
          topic_weights?: Json
          updated_at?: string
          user_id: string
        }
        Update: {
          counter_rate?: number
          created_at?: string
          daily_minutes?: number
          excluded_topics?: string[]
          interrupt_rate?: number
          media_kinds?: Database["public"]["Enums"]["work_kind"][]
          novelty?: number
          onboarded_at?: string | null
          spoilers?: Database["public"]["Enums"]["spoiler_level"]
          technical_level?: number
          topic_weights?: Json
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_path: string | null
          bio: string | null
          created_at: string
          display_name: string | null
          handle: string
          id: string
          updated_at: string
        }
        Insert: {
          avatar_path?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          handle: string
          id: string
          updated_at?: string
        }
        Update: {
          avatar_path?: string | null
          bio?: string | null
          created_at?: string
          display_name?: string | null
          handle?: string
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      progress: {
        Row: {
          completed_at: string | null
          last_ordinal: number
          percent: number
          summary_id: string
          updated_at: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          last_ordinal?: number
          percent?: number
          summary_id: string
          updated_at?: string
          user_id: string
        }
        Update: {
          completed_at?: string | null
          last_ordinal?: number
          percent?: number
          summary_id?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "progress_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
        ]
      }
      pull_relations: {
        Row: {
          created_at: string
          from_pull_id: string
          kind: Database["public"]["Enums"]["relation_kind"]
          rationale: string | null
          to_pull_id: string
          weight: number
        }
        Insert: {
          created_at?: string
          from_pull_id: string
          kind: Database["public"]["Enums"]["relation_kind"]
          rationale?: string | null
          to_pull_id: string
          weight?: number
        }
        Update: {
          created_at?: string
          from_pull_id?: string
          kind?: Database["public"]["Enums"]["relation_kind"]
          rationale?: string | null
          to_pull_id?: string
          weight?: number
        }
        Relationships: [
          {
            foreignKeyName: "pull_relations_from_pull_id_fkey"
            columns: ["from_pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pull_relations_to_pull_id_fkey"
            columns: ["to_pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      pulls: {
        Row: {
          body: string
          created_at: string
          embedding: string | null
          estimated_read_seconds: number
          example: string | null
          explanation: string | null
          headline: string
          id: string
          image_asset_id: string | null
          ordinal: number
          spoiler_level: Database["public"]["Enums"]["spoiler_level"]
          summary_id: string
          updated_at: string
          why_it_matters: string | null
        }
        Insert: {
          body: string
          created_at?: string
          embedding?: string | null
          estimated_read_seconds?: number
          example?: string | null
          explanation?: string | null
          headline: string
          id?: string
          image_asset_id?: string | null
          ordinal: number
          spoiler_level?: Database["public"]["Enums"]["spoiler_level"]
          summary_id: string
          updated_at?: string
          why_it_matters?: string | null
        }
        Update: {
          body?: string
          created_at?: string
          embedding?: string | null
          estimated_read_seconds?: number
          example?: string | null
          explanation?: string | null
          headline?: string
          id?: string
          image_asset_id?: string | null
          ordinal?: number
          spoiler_level?: Database["public"]["Enums"]["spoiler_level"]
          summary_id?: string
          updated_at?: string
          why_it_matters?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "pulls_image_asset_fk"
            columns: ["image_asset_id"]
            isOneToOne: false
            referencedRelation: "artworks"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "pulls_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
        ]
      }
      quiz_questions: {
        Row: {
          answer: string
          created_at: string
          distractors: Json
          id: string
          kind: string
          prompt: string
          pull_id: string
        }
        Insert: {
          answer: string
          created_at?: string
          distractors?: Json
          id?: string
          kind?: string
          prompt: string
          pull_id: string
        }
        Update: {
          answer?: string
          created_at?: string
          distractors?: Json
          id?: string
          kind?: string
          prompt?: string
          pull_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "quiz_questions_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
        ]
      }
      rate_limits: {
        Row: {
          bucket: string
          count: number
          user_id: string
          window_start: string
        }
        Insert: {
          bucket: string
          count?: number
          user_id: string
          window_start: string
        }
        Update: {
          bucket?: string
          count?: number
          user_id?: string
          window_start?: string
        }
        Relationships: []
      }
      reports: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          reason: string
          reporter_id: string | null
          status: string
          target_id: string
          target_type: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          reason: string
          reporter_id?: string | null
          status?: string
          target_id: string
          target_type: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          reason?: string
          reporter_id?: string | null
          status?: string
          target_id?: string
          target_type?: string
        }
        Relationships: []
      }
      rights_requests: {
        Row: {
          claimant_email: string
          claimant_name: string
          id: string
          notice_body: string
          received_at: string
          resolution: string | null
          resolved_at: string | null
          status: string
          summary_id: string | null
          work_id: string | null
        }
        Insert: {
          claimant_email: string
          claimant_name: string
          id?: string
          notice_body: string
          received_at?: string
          resolution?: string | null
          resolved_at?: string | null
          status?: string
          summary_id?: string | null
          work_id?: string | null
        }
        Update: {
          claimant_email?: string
          claimant_name?: string
          id?: string
          notice_body?: string
          received_at?: string
          resolution?: string | null
          resolved_at?: string | null
          status?: string
          summary_id?: string | null
          work_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "rights_requests_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "rights_requests_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_items: {
        Row: {
          archived: boolean
          created_at: string
          id: string
          note: string | null
          pull_id: string | null
          read_later: boolean
          stash_id: string | null
          summary_id: string | null
          user_id: string
        }
        Insert: {
          archived?: boolean
          created_at?: string
          id?: string
          note?: string | null
          pull_id?: string | null
          read_later?: boolean
          stash_id?: string | null
          summary_id?: string | null
          user_id: string
        }
        Update: {
          archived?: boolean
          created_at?: string
          id?: string
          note?: string | null
          pull_id?: string | null
          read_later?: boolean
          stash_id?: string | null
          summary_id?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_items_pull_id_fkey"
            columns: ["pull_id"]
            isOneToOne: false
            referencedRelation: "pulls"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_items_stash_id_fkey"
            columns: ["stash_id"]
            isOneToOne: false
            referencedRelation: "stashes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_items_summary_id_fkey"
            columns: ["summary_id"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
        ]
      }
      session_seeds: {
        Row: {
          cards_seen: number
          ended_at: string | null
          id: string
          interrupts_shown: number
          seed: number
          started_at: string
          user_id: string
        }
        Insert: {
          cards_seen?: number
          ended_at?: string | null
          id?: string
          interrupts_shown?: number
          seed: number
          started_at?: string
          user_id: string
        }
        Update: {
          cards_seen?: number
          ended_at?: string | null
          id?: string
          interrupts_shown?: number
          seed?: number
          started_at?: string
          user_id?: string
        }
        Relationships: []
      }
      stashes: {
        Row: {
          cover_path: string | null
          created_at: string
          description: string | null
          id: string
          is_smart: boolean
          name: string
          parent_id: string | null
          position: number
          query: Json | null
          updated_at: string
          user_id: string
          visibility: Database["public"]["Enums"]["visibility"]
        }
        Insert: {
          cover_path?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_smart?: boolean
          name: string
          parent_id?: string | null
          position?: number
          query?: Json | null
          updated_at?: string
          user_id: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Update: {
          cover_path?: string | null
          created_at?: string
          description?: string | null
          id?: string
          is_smart?: boolean
          name?: string
          parent_id?: string | null
          position?: number
          query?: Json | null
          updated_at?: string
          user_id?: string
          visibility?: Database["public"]["Enums"]["visibility"]
        }
        Relationships: [
          {
            foreignKeyName: "stashes_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "stashes"
            referencedColumns: ["id"]
          },
        ]
      }
      summaries: {
        Row: {
          author_id: string | null
          created_at: string
          difficulty: number
          edition_id: string | null
          elevator_pitch: string | null
          forked_from: string | null
          id: string
          published_at: string | null
          reading_minutes: number
          sections: Json
          spoiler_level: Database["public"]["Enums"]["spoiler_level"]
          status: Database["public"]["Enums"]["publish_status"]
          title: string
          updated_at: string
          version: number
          visibility: Database["public"]["Enums"]["visibility"]
          why_it_matters: string | null
          work_id: string
        }
        Insert: {
          author_id?: string | null
          created_at?: string
          difficulty?: number
          edition_id?: string | null
          elevator_pitch?: string | null
          forked_from?: string | null
          id?: string
          published_at?: string | null
          reading_minutes?: number
          sections?: Json
          spoiler_level?: Database["public"]["Enums"]["spoiler_level"]
          status?: Database["public"]["Enums"]["publish_status"]
          title: string
          updated_at?: string
          version?: number
          visibility?: Database["public"]["Enums"]["visibility"]
          why_it_matters?: string | null
          work_id: string
        }
        Update: {
          author_id?: string | null
          created_at?: string
          difficulty?: number
          edition_id?: string | null
          elevator_pitch?: string | null
          forked_from?: string | null
          id?: string
          published_at?: string | null
          reading_minutes?: number
          sections?: Json
          spoiler_level?: Database["public"]["Enums"]["spoiler_level"]
          status?: Database["public"]["Enums"]["publish_status"]
          title?: string
          updated_at?: string
          version?: number
          visibility?: Database["public"]["Enums"]["visibility"]
          why_it_matters?: string | null
          work_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "summaries_edition_id_fkey"
            columns: ["edition_id"]
            isOneToOne: false
            referencedRelation: "editions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "summaries_forked_from_fkey"
            columns: ["forked_from"]
            isOneToOne: false
            referencedRelation: "summaries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "summaries_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      topics: {
        Row: {
          created_at: string
          id: string
          label: string
          parent_id: string | null
          slug: string
        }
        Insert: {
          created_at?: string
          id?: string
          label: string
          parent_id?: string | null
          slug: string
        }
        Update: {
          created_at?: string
          id?: string
          label?: string
          parent_id?: string | null
          slug?: string
        }
        Relationships: [
          {
            foreignKeyName: "topics_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
        ]
      }
      user_knowledge_vectors: {
        Row: {
          embedding: string | null
          idea_count: number
          updated_at: string
          user_id: string
        }
        Insert: {
          embedding?: string | null
          idea_count?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          embedding?: string | null
          idea_count?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      work_contributors: {
        Row: {
          contributor_id: string
          ordinal: number
          role: string
          work_id: string
        }
        Insert: {
          contributor_id: string
          ordinal?: number
          role?: string
          work_id: string
        }
        Update: {
          contributor_id?: string
          ordinal?: number
          role?: string
          work_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_contributors_contributor_id_fkey"
            columns: ["contributor_id"]
            isOneToOne: false
            referencedRelation: "contributors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_contributors_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      work_topics: {
        Row: {
          topic_id: string
          weight: number
          work_id: string
        }
        Insert: {
          topic_id: string
          weight?: number
          work_id: string
        }
        Update: {
          topic_id?: string
          weight?: number
          work_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "work_topics_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "topics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "work_topics_work_id_fkey"
            columns: ["work_id"]
            isOneToOne: false
            referencedRelation: "works"
            referencedColumns: ["id"]
          },
        ]
      }
      works: {
        Row: {
          created_at: string
          description: string | null
          external_ids: Json
          id: string
          kind: Database["public"]["Enums"]["work_kind"]
          quality_score: number
          rights_status: Database["public"]["Enums"]["rights_status"]
          slug: string
          subtitle: string | null
          title: string
          trust_score: number
          updated_at: string
          year: number | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          external_ids?: Json
          id?: string
          kind: Database["public"]["Enums"]["work_kind"]
          quality_score?: number
          rights_status?: Database["public"]["Enums"]["rights_status"]
          slug: string
          subtitle?: string | null
          title: string
          trust_score?: number
          updated_at?: string
          year?: number | null
        }
        Update: {
          created_at?: string
          description?: string | null
          external_ids?: Json
          id?: string
          kind?: Database["public"]["Enums"]["work_kind"]
          quality_score?: number
          rights_status?: Database["public"]["Enums"]["rights_status"]
          slug?: string
          subtitle?: string | null
          title?: string
          trust_score?: number
          updated_at?: string
          year?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      advance_generation_job: {
        Args: { p_from_step: string; p_job_id: string; p_to_step?: string }
        Returns: boolean
      }
      archive_generation_message: {
        Args: { p_msg_id: number }
        Returns: boolean
      }
      claim_generation_messages: {
        Args: { p_count?: number; p_visibility_seconds?: number }
        Returns: {
          message: Json
          msg_id: number
        }[]
      }
      disable_generation_dispatcher: { Args: never; Returns: string }
      dismissal_damping: { Args: { p_user_id: string }; Returns: number }
      due_pressure: { Args: { p_user_id: string }; Returns: number }
      enable_generation_dispatcher: {
        Args: {
          p_project_url: string
          p_seconds?: number
          p_service_key: string
        }
        Returns: string
      }
      enqueue_generation_job: { Args: { p_target: Json }; Returns: Json }
      get_due_reviews: { Args: { p_limit?: number }; Returns: Json }
      get_feed: {
        Args: {
          p_cards_before?: number
          p_last_placed?: number
          p_limit?: number
          p_page?: number
          p_seed?: number
          p_used_budget?: number
        }
        Returns: Json
      }
      get_source_delta: { Args: { p_work_id: string }; Returns: Json }
      grade_recall: {
        Args: {
          p_grade: Database["public"]["Enums"]["recall_grade"]
          p_pull_id: string
        }
        Returns: {
          acquired_via: Database["public"]["Enums"]["acquisition"]
          difficulty: number
          lapses: number
          last_seen_at: string
          next_due_at: string
          pull_id: string
          reps: number
          stability: number
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "knowledge_states"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      plan_interleave: {
        Args: {
          p_cards_before?: number
          p_last_placed?: number
          p_page: number
          p_page_size: number
          p_seed: number
          p_used_budget?: number
          p_user_id: string
        }
        Returns: {
          kind: Database["public"]["Enums"]["interrupt_kind"]
          slot_index: number
        }[]
      }
      record_interrupt: {
        Args: {
          p_grade?: Database["public"]["Enums"]["recall_grade"]
          p_kind: Database["public"]["Enums"]["interrupt_kind"]
          p_latency?: number
          p_pull_id: string
          p_response: Database["public"]["Enums"]["interrupt_response"]
          p_session?: string
          p_slot: number
        }
        Returns: undefined
      }
      record_job_step: {
        Args: {
          p_attempt: number
          p_billable?: boolean
          p_cost_cents: number
          p_duration_ms: number
          p_input_tokens: number
          p_job_id: string
          p_model: string
          p_output_tokens: number
          p_prompt_version: string
          p_provider: string
          p_step: string
        }
        Returns: string
      }
      record_read: {
        Args: { p_dwell_ms?: number; p_position?: number; p_pull_id: string }
        Returns: undefined
      }
      refresh_knowledge_vector: {
        Args: { p_user_id?: string }
        Returns: undefined
      }
      retrievability: {
        Args: { p_at?: string; p_last_seen: string; p_stability: number }
        Returns: number
      }
      seeded_unit: {
        Args: { page: number; salt?: string; seed: number; slot: number }
        Returns: number
      }
      set_conviction: {
        Args: {
          p_confidence?: number
          p_pull_id: string
          p_rationale?: string
          p_stance: Database["public"]["Enums"]["stance"]
        }
        Returns: {
          confidence: number
          created_at: string
          id: string
          pull_id: string
          rationale: string | null
          stance: Database["public"]["Enums"]["stance"]
          superseded_by: string | null
          user_id: string
        }
        SetofOptions: {
          from: "*"
          to: "convictions"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      summary_is_readable: {
        Args: { s: Database["public"]["Tables"]["summaries"]["Row"] }
        Returns: boolean
      }
      synthetic_embedding: { Args: { p_axes: Json }; Returns: string }
      topic_affinity: {
        Args: { p_weights: Json; p_work_id: string }
        Returns: number
      }
    }
    Enums: {
      acquisition: "read" | "saved" | "explained" | "quizzed" | "probed"
      curator_kind: "editorial" | "community" | "algorithmic"
      interrupt_kind:
        | "recall"
        | "say_it_back"
        | "conviction"
        | "counterpull"
        | "delta_probe"
      interrupt_response: "answered" | "dismissed" | "expired"
      job_status: "queued" | "running" | "succeeded" | "failed" | "cancelled"
      locator_type: "page" | "chapter" | "timestamp" | "section" | "url"
      publish_status: "draft" | "published" | "retired"
      recall_grade: "forgot" | "hard" | "good" | "easy"
      relation_kind:
        | "related"
        | "opposes"
        | "elaborates"
        | "ancestor"
        | "descendant"
      rights_status:
        | "public_domain"
        | "licensed"
        | "user_owned"
        | "public_reference"
        | "community"
        | "review_required"
      spoiler_level: "none" | "mild" | "full"
      stance: "agree" | "disagree" | "unsure"
      visibility: "private" | "unlisted" | "public"
      work_kind:
        | "book"
        | "film"
        | "documentary"
        | "podcast"
        | "paper"
        | "essay"
        | "lecture"
        | "video"
        | "interview"
        | "other"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      acquisition: ["read", "saved", "explained", "quizzed", "probed"],
      curator_kind: ["editorial", "community", "algorithmic"],
      interrupt_kind: [
        "recall",
        "say_it_back",
        "conviction",
        "counterpull",
        "delta_probe",
      ],
      interrupt_response: ["answered", "dismissed", "expired"],
      job_status: ["queued", "running", "succeeded", "failed", "cancelled"],
      locator_type: ["page", "chapter", "timestamp", "section", "url"],
      publish_status: ["draft", "published", "retired"],
      recall_grade: ["forgot", "hard", "good", "easy"],
      relation_kind: [
        "related",
        "opposes",
        "elaborates",
        "ancestor",
        "descendant",
      ],
      rights_status: [
        "public_domain",
        "licensed",
        "user_owned",
        "public_reference",
        "community",
        "review_required",
      ],
      spoiler_level: ["none", "mild", "full"],
      stance: ["agree", "disagree", "unsure"],
      visibility: ["private", "unlisted", "public"],
      work_kind: [
        "book",
        "film",
        "documentary",
        "podcast",
        "paper",
        "essay",
        "lecture",
        "video",
        "interview",
        "other",
      ],
    },
  },
} as const

