/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as vendor from "./vendor/index.js";

export { reflect } from "./baml/index.js";

/**
 * Attributes:
 *   title
 *   elevatorPitch
 *   whyItMatters
 *   pulls: A summary with no ideas in it is not a summary.
 *   topics: One to four, most central first.
 *     
 *     Bounded at both ends deliberately. Unbounded below, an empty array
 *     satisfies the shape and the work is filed under nothing -- `topic_affinity`
 *     then returns 0.0, and that term is 28% of the score in `get_feed`, so the
 *     feature fails silently rather than visibly.
 *     
 *     The bound is NOT declared here, and do not put it back with `@assert`.
 *     v1 accepts v0's `@assert(name, {{ ... }})` without a parse error and then
 *     ignores it: `baml describe` does not show it, `baml.json.schema` lowers no
 *     `minItems`/`maxItems`, and `$parse` on `{"topics": []}` returns an empty
 *     list rather than throwing. Verified against 0.17.0. An annotation that
 *     looks like enforcement and is not is worse than none, so the bound lives
 *     in `BOUNDS` in scripts/export.mjs, reaches the model through Gemini's
 *     `responseSchema`, and is pinned by src/schema.test.ts.
 */
export class CanonicalSummary$stream {
  title!: string | null;
  elevatorPitch!: string | null;
  whyItMatters!: string | null;
  pulls!: Pull$stream[];
  topics!: TopicSlug[];
  constructor(init: {
    title: string | null;
    elevatorPitch: string | null;
    whyItMatters: string | null;
    pulls: Pull$stream[];
    topics: TopicSlug[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Why one particular wrong option is wrong.
 * 
 * An array of pairs rather than a map from distractor to reason, because Gemini's
 * schema dialect has no map type. `whyWrong` in `apps/web/src/lib/activities.ts`
 * reads exactly this shape and matches on `distractor`.
 *
 * Attributes:
 *   distractor: The wrong option this explains. Must be one of the question's `distractors`
 *     verbatim, or the client cannot match it to what the reader picked.
 *   why: One sentence on the mistake it represents -- not a restatement of the answer.
 */
export class DistractorRationale$stream {
  distractor!: string | null;
  why!: string | null;
  constructor(init: {
    distractor: string | null;
    why: string | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One atomic idea that stands on its own out of context, structured for progressive depth.
 *
 * Attributes:
 *   headline: Shortest stop: states the idea rather than teasing it.
 *   body: Short stop: the core claim and reasoning in 1-3 sentences.
 *   whyItMatters: Medium stop (impact): what changes if the reader believes it -- not a restatement of the body.
 *   example: Medium stop (concrete grounding): a real case study, historical instance, demonstration, or thought experiment.
 *   explanation: Long stop (in full): the deep-dive analytical breakdown, mechanism, counterarguments, or derivation.
 *   questions: Up to three, of different kinds, most useful first. EMPTY rather than
 *     invented when the source is too thin to support a fair question --
 *     `get_due_reviews` copes with a pull that has none, and a question with a
 *     made-up answer is worse than no question at all.
 *     
 *     AT MOST ONE OF EACH KIND. `quiz_questions_pull_kind_key` is unique on
 *     `(pull_id, kind)`, so two questions of the same kind for one idea are not two
 *     rows -- `questionsToWrite` keeps the first and drops the rest, because an
 *     upsert cannot touch the same row twice in one statement.
 */
export class Pull$stream {
  headline!: string | null;
  body!: string | null;
  whyItMatters!: string | null;
  example!: string | null;
  explanation!: string | null;
  questions!: RecallQuestion$stream[];
  constructor(init: {
    headline: string | null;
    body: string | null;
    whyItMatters: string | null;
    example: string | null;
    explanation: string | null;
    questions: RecallQuestion$stream[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * One question, produced by the same call that produced the idea.
 * 
 * Law 2 is why this rides the synthesis call rather than being its own function:
 * questions are generated once per canonical summary and read by thousands, and a
 * second request per summary would be a second bill for something the model has
 * already read the source for. Grading is a comparison the client does, so no
 * model goes near the read path.
 *
 * Attributes:
 *   kind
 *   prompt
 *   answer: The right answer. For `mcq` it is the option that is correct; for `cloze` it
 *     is what fills the blank.
 *   distractors: The WRONG options, never including the answer. Empty for `recall` and
 *     `cloze`; `mcq` needs at least two, or the question cannot be got wrong and
 *     the database refuses it.
 *   cloze: The sentence with the answer removed, marked with four underscores. Required
 *     for `cloze` and omitted otherwise.
 *   explanation: Why the answer is the answer, shown after grading whatever the reader picked.
 *   rationale: One entry per distractor, for `mcq`. Empty for the kinds that have none.
 */
export class RecallQuestion$stream {
  kind!: QuestionKind | null;
  prompt!: string | null;
  answer!: string | null;
  distractors!: string[];
  cloze!: string | null;
  explanation!: string | null;
  rationale!: DistractorRationale$stream[];
  constructor(init: {
    kind: QuestionKind | null;
    prompt: string | null;
    answer: string | null;
    distractors: string[];
    cloze: string | null;
    explanation: string | null;
    rationale: DistractorRationale$stream[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Every `topics.slug` a generated work may be filed under.
 * 
 * Mirrors `TOPIC_SLUGS` in `supabase/functions/_shared/providers.ts`, which in
 * turn mirrors the taxonomy seeded by `20260831025500_topics_with_something_behind_them`.
 * An enum rather than a string: a slug outside the list is rejected at the
 * boundary instead of being discovered by `upsertWork`, which silently drops
 * what it cannot look up. If the taxonomy migration changes, this changes in
 * the same commit.
 */
export enum TopicSlug {
  Philosophy = "Philosophy",
  Ethics = "Ethics",
  Stoicism = "Stoicism",
  Logic = "Logic",
  Metaphysics = "Metaphysics",
  Aesthetics = "Aesthetics",
  Psychology = "Psychology",
  Attention = "Attention",
  Habits = "Habits",
  Learning = "Learning",
  Emotion = "Emotion",
  Science = "Science",
  Evolution = "Evolution",
  Physics = "Physics",
  Chemistry = "Chemistry",
  Astronomy = "Astronomy",
  Medicine = "Medicine",
  Society = "Society",
  Economics = "Economics",
  Liberty = "Liberty",
  Government = "Government",
  Justice = "Justice",
  Education = "Education",
  ArtsAndLetters = "ArtsAndLetters",
  Literature = "Literature",
  Rhetoric = "Rhetoric",
  Criticism = "Criticism",
  History = "History",
  Biography = "Biography",
  Revolutions = "Revolutions",
  Mathematics = "Mathematics",
  Computation = "Computation",
  Architecture = "Architecture",
  WorldPhilosophy = "WorldPhilosophy",
  Strategy = "Strategy",
  Ecology = "Ecology",
}

/**
 * The kinds a generated question may take.
 * 
 * Three of the six `quiz_questions.kind` accepts
 * (`20260905120000_a_question_that_can_be_wrong.sql`). `ordering` and `scenario`
 * are in the database because the column should not have to change when they
 * arrive; `short_answer` is what a reader writes rather than what is generated.
 * Asking for a kind nothing renders would spend tokens on a row `Review` cannot
 * use.
 * 
 * Aliased to the database's own values. `QuestionKind.Mcq` is `"mcq"` at the
 * boundary and `"Mcq"` in generated TypeScript -- never use the generated
 * identifier as a database value.
 */
export enum QuestionKind {
  Recall = "Recall",
  Mcq = "Mcq",
  Cloze = "Cloze",
}

/**
 * Why one particular wrong option is wrong.
 * 
 * An array of pairs rather than a map from distractor to reason, because Gemini's
 * schema dialect has no map type. `whyWrong` in `apps/web/src/lib/activities.ts`
 * reads exactly this shape and matches on `distractor`.
 *
 * Attributes:
 *   distractor: The wrong option this explains. Must be one of the question's `distractors`
 *     verbatim, or the client cannot match it to what the reader picked.
 *   why: One sentence on the mistake it represents -- not a restatement of the answer.
 */
export class DistractorRationale {
  distractor!: string;
  why!: string;
  constructor(init: {
    distractor: string;
    why: string;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One question, produced by the same call that produced the idea.
 * 
 * Law 2 is why this rides the synthesis call rather than being its own function:
 * questions are generated once per canonical summary and read by thousands, and a
 * second request per summary would be a second bill for something the model has
 * already read the source for. Grading is a comparison the client does, so no
 * model goes near the read path.
 *
 * Attributes:
 *   kind
 *   prompt
 *   answer: The right answer. For `mcq` it is the option that is correct; for `cloze` it
 *     is what fills the blank.
 *   distractors: The WRONG options, never including the answer. Empty for `recall` and
 *     `cloze`; `mcq` needs at least two, or the question cannot be got wrong and
 *     the database refuses it.
 *   cloze: The sentence with the answer removed, marked with four underscores. Required
 *     for `cloze` and omitted otherwise.
 *   explanation: Why the answer is the answer, shown after grading whatever the reader picked.
 *   rationale: One entry per distractor, for `mcq`. Empty for the kinds that have none.
 */
export class RecallQuestion {
  kind!: QuestionKind;
  prompt!: string;
  answer!: string;
  distractors!: string[];
  cloze!: string | null;
  explanation!: string | null;
  rationale!: DistractorRationale[];
  constructor(init: {
    kind: QuestionKind;
    prompt: string;
    answer: string;
    distractors: string[];
    cloze: string | null;
    explanation: string | null;
    rationale: DistractorRationale[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * One atomic idea that stands on its own out of context, structured for progressive depth.
 *
 * Attributes:
 *   headline: Shortest stop: states the idea rather than teasing it.
 *   body: Short stop: the core claim and reasoning in 1-3 sentences.
 *   whyItMatters: Medium stop (impact): what changes if the reader believes it -- not a restatement of the body.
 *   example: Medium stop (concrete grounding): a real case study, historical instance, demonstration, or thought experiment.
 *   explanation: Long stop (in full): the deep-dive analytical breakdown, mechanism, counterarguments, or derivation.
 *   questions: Up to three, of different kinds, most useful first. EMPTY rather than
 *     invented when the source is too thin to support a fair question --
 *     `get_due_reviews` copes with a pull that has none, and a question with a
 *     made-up answer is worse than no question at all.
 *     
 *     AT MOST ONE OF EACH KIND. `quiz_questions_pull_kind_key` is unique on
 *     `(pull_id, kind)`, so two questions of the same kind for one idea are not two
 *     rows -- `questionsToWrite` keeps the first and drops the rest, because an
 *     upsert cannot touch the same row twice in one statement.
 */
export class Pull {
  headline!: string;
  body!: string;
  whyItMatters!: string;
  example!: string | null;
  explanation!: string | null;
  questions!: RecallQuestion[];
  constructor(init: {
    headline: string;
    body: string;
    whyItMatters: string;
    example: string | null;
    explanation: string | null;
    questions: RecallQuestion[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Attributes:
 *   title
 *   elevatorPitch
 *   whyItMatters
 *   pulls: A summary with no ideas in it is not a summary.
 *   topics: One to four, most central first.
 *     
 *     Bounded at both ends deliberately. Unbounded below, an empty array
 *     satisfies the shape and the work is filed under nothing -- `topic_affinity`
 *     then returns 0.0, and that term is 28% of the score in `get_feed`, so the
 *     feature fails silently rather than visibly.
 *     
 *     The bound is NOT declared here, and do not put it back with `@assert`.
 *     v1 accepts v0's `@assert(name, {{ ... }})` without a parse error and then
 *     ignores it: `baml describe` does not show it, `baml.json.schema` lowers no
 *     `minItems`/`maxItems`, and `$parse` on `{"topics": []}` returns an empty
 *     list rather than throwing. Verified against 0.17.0. An annotation that
 *     looks like enforcement and is not is worse than none, so the bound lives
 *     in `BOUNDS` in scripts/export.mjs, reaches the model through Gemini's
 *     `responseSchema`, and is pinned by src/schema.test.ts.
 */
export class CanonicalSummary {
  title!: string;
  elevatorPitch!: string;
  whyItMatters!: string;
  pulls!: Pull[];
  topics!: TopicSlug[];
  constructor(init: {
    title: string;
    elevatorPitch: string;
    whyItMatters: string;
    pulls: Pull[];
    topics: TopicSlug[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws UnknownError
 * @throws CompilationError
 */
export const WriteCanonicalSummary = defineFunction("user.WriteCanonicalSummary", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => CanonicalSummary;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws UnknownError
 * @throws CompilationError
 */
export const WriteCanonicalSummary_async = defineFunction("user.WriteCanonicalSummary", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws LlmClient
 */
export const WriteCanonicalSummary$parse = defineFunction("user.WriteCanonicalSummary$parse", "sync", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => CanonicalSummary;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws LlmClient
 */
export const WriteCanonicalSummary$parse_async = defineFunction("user.WriteCanonicalSummary$parse", "async", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidRequest
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws CompilationError
 */
export const WriteCanonicalSummary$render_prompt = defineFunction("user.WriteCanonicalSummary$render_prompt", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Prompt;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidRequest
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws CompilationError
 */
export const WriteCanonicalSummary$render_prompt_async = defineFunction("user.WriteCanonicalSummary$render_prompt", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 */
export const WriteCanonicalSummary$stream = defineFunction("user.WriteCanonicalSummary$stream", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.stream.Stream<CanonicalSummary$stream | null, CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 */
export const WriteCanonicalSummary$stream_async = defineFunction("user.WriteCanonicalSummary$stream", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.stream.Stream<CanonicalSummary$stream | null, CanonicalSummary>>;
