/* eslint-disable */
// prettier-ignore
// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ pnpm add @boundaryml/baml-bridge
//  $ npm install @boundaryml/baml-bridge
//  $ yarn add @boundaryml/baml-bridge
//
// ----------------------------------------------------------------------------
// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate

import { defineFunction, initializeRuntimeFromBytecode, setTypeMap, type BamlCallContext } from "@boundaryml/baml-bridge";
import * as _inlinedbaml from "./_inlinedbaml.js";
import { _TYPE_MAP } from "./_typemap.js";
import type * as ai from "./ai/index.js";

initializeRuntimeFromBytecode(_inlinedbaml.BYTECODE, _inlinedbaml.BAML_TOML);
setTypeMap(_TYPE_MAP);

export * as ai from "./ai/index.js";
export * as baml from "./baml/index.js";
export * as vendor from "./vendor/index.js";

export { reflect } from "./baml/index.js";

/**
 * Attributes:
 *   title
 *   elevatorPitch
 *   whyItMatters
 *   pulls: A summary with no ideas in it is not a summary.
 *   topics: One to four, most central first.
 *     
 *     Bounded at both ends deliberately. Unbounded below, an empty array
 *     satisfies the shape and the work is filed under nothing -- `topic_affinity`
 *     then returns 0.0, and that term is 28% of the score in `get_feed`, so the
 *     feature fails silently rather than visibly.
 */
export class CanonicalSummary$stream {
  title!: string | null;
  elevatorPitch!: string | null;
  whyItMatters!: string | null;
  pulls!: Pull$stream[];
  topics!: TopicSlug[];
  constructor(init: {
    title: string | null;
    elevatorPitch: string | null;
    whyItMatters: string | null;
    pulls: Pull$stream[];
    topics: TopicSlug[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * One atomic idea that stands on its own out of context, structured for progressive depth.
 *
 * Attributes:
 *   headline: Shortest stop: states the idea rather than teasing it.
 *   body: Short stop: the core claim and reasoning in 1-3 sentences.
 *   whyItMatters: Medium stop (impact): what changes if the reader believes it -- not a restatement of the body.
 *   example: Medium stop (concrete grounding): a real case study, historical instance, demonstration, or thought experiment.
 *   explanation: Long stop (in full): the deep-dive analytical breakdown, mechanism, counterarguments, or derivation.
 *   question: Omitted rather than invented when the source is too thin to support a fair
 *     question. `get_due_reviews` already copes with a pull that has none.
 */
export class Pull$stream {
  headline!: string | null;
  body!: string | null;
  whyItMatters!: string | null;
  example!: string | null;
  explanation!: string | null;
  question!: RecallQuestion$stream | null;
  constructor(init: {
    headline: string | null;
    body: string | null;
    whyItMatters: string | null;
    example: string | null;
    explanation: string | null;
    question: RecallQuestion$stream | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * One recall question, produced by the same call that produced the idea.
 * 
 * `distractors` are what turn the recall interrupt from a self-graded reveal
 * into something that can be wrong — and grading three wrong answers against
 * one right one is a comparison the client does, so no model goes near the
 * read path.
 */
export class RecallQuestion$stream {
  prompt!: string | null;
  answer!: string | null;
  distractors!: string[];
  constructor(init: {
    prompt: string | null;
    answer: string | null;
    distractors: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Every `topics.slug` a generated work may be filed under.
 * 
 * Mirrors `TOPIC_SLUGS` in `supabase/functions/_shared/providers.ts`, which in
 * turn mirrors the taxonomy seeded by `20260831025500_topics_with_something_behind_them`.
 * An enum rather than a string: a slug outside the list is rejected at the
 * boundary instead of being discovered by `upsertWork`, which silently drops
 * what it cannot look up. If the taxonomy migration changes, this changes in
 * the same commit.
 */
export enum TopicSlug {
  Philosophy = "Philosophy",
  Ethics = "Ethics",
  Stoicism = "Stoicism",
  Logic = "Logic",
  Metaphysics = "Metaphysics",
  Aesthetics = "Aesthetics",
  Psychology = "Psychology",
  Attention = "Attention",
  Habits = "Habits",
  Learning = "Learning",
  Emotion = "Emotion",
  Science = "Science",
  Evolution = "Evolution",
  Physics = "Physics",
  Chemistry = "Chemistry",
  Astronomy = "Astronomy",
  Medicine = "Medicine",
  Society = "Society",
  Economics = "Economics",
  Liberty = "Liberty",
  Government = "Government",
  Justice = "Justice",
  Education = "Education",
  ArtsAndLetters = "ArtsAndLetters",
  Literature = "Literature",
  Rhetoric = "Rhetoric",
  Criticism = "Criticism",
  History = "History",
  Biography = "Biography",
  Revolutions = "Revolutions",
  Mathematics = "Mathematics",
  Computation = "Computation",
  Architecture = "Architecture",
  WorldPhilosophy = "WorldPhilosophy",
  Strategy = "Strategy",
  Ecology = "Ecology",
}

/**
 * One recall question, produced by the same call that produced the idea.
 * 
 * `distractors` are what turn the recall interrupt from a self-graded reveal
 * into something that can be wrong — and grading three wrong answers against
 * one right one is a comparison the client does, so no model goes near the
 * read path.
 */
export class RecallQuestion {
  prompt!: string;
  answer!: string;
  distractors!: string[];
  constructor(init: {
    prompt: string;
    answer: string;
    distractors: string[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * One atomic idea that stands on its own out of context, structured for progressive depth.
 *
 * Attributes:
 *   headline: Shortest stop: states the idea rather than teasing it.
 *   body: Short stop: the core claim and reasoning in 1-3 sentences.
 *   whyItMatters: Medium stop (impact): what changes if the reader believes it -- not a restatement of the body.
 *   example: Medium stop (concrete grounding): a real case study, historical instance, demonstration, or thought experiment.
 *   explanation: Long stop (in full): the deep-dive analytical breakdown, mechanism, counterarguments, or derivation.
 *   question: Omitted rather than invented when the source is too thin to support a fair
 *     question. `get_due_reviews` already copes with a pull that has none.
 */
export class Pull {
  headline!: string;
  body!: string;
  whyItMatters!: string;
  example!: string | null;
  explanation!: string | null;
  question!: RecallQuestion | null;
  constructor(init: {
    headline: string;
    body: string;
    whyItMatters: string;
    example: string | null;
    explanation: string | null;
    question: RecallQuestion | null;
  }) {
    Object.assign(this, init);
  }
}

/**
 * Attributes:
 *   title
 *   elevatorPitch
 *   whyItMatters
 *   pulls: A summary with no ideas in it is not a summary.
 *   topics: One to four, most central first.
 *     
 *     Bounded at both ends deliberately. Unbounded below, an empty array
 *     satisfies the shape and the work is filed under nothing -- `topic_affinity`
 *     then returns 0.0, and that term is 28% of the score in `get_feed`, so the
 *     feature fails silently rather than visibly.
 */
export class CanonicalSummary {
  title!: string;
  elevatorPitch!: string;
  whyItMatters!: string;
  pulls!: Pull[];
  topics!: TopicSlug[];
  constructor(init: {
    title: string;
    elevatorPitch: string;
    whyItMatters: string;
    pulls: Pull[];
    topics: TopicSlug[];
  }) {
    Object.assign(this, init);
  }
}

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws UnknownError
 * @throws CompilationError
 */
export const WriteCanonicalSummary = defineFunction("user.WriteCanonicalSummary", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => CanonicalSummary;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws UnknownError
 * @throws CompilationError
 */
export const WriteCanonicalSummary_async = defineFunction("user.WriteCanonicalSummary", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws LlmClient
 */
export const WriteCanonicalSummary$parse = defineFunction("user.WriteCanonicalSummary$parse", "sync", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => CanonicalSummary;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws LlmClient
 */
export const WriteCanonicalSummary$parse_async = defineFunction("user.WriteCanonicalSummary$parse", "async", ["json"]) as (json: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidRequest
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws CompilationError
 */
export const WriteCanonicalSummary$render_prompt = defineFunction("user.WriteCanonicalSummary$render_prompt", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.Prompt;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 * @throws InvalidRequest
 * @throws InvalidArgument
 * @throws Io
 * @throws ParseError
 * @throws CompilationError
 */
export const WriteCanonicalSummary$render_prompt_async = defineFunction("user.WriteCanonicalSummary$render_prompt", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.Prompt>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 */
export const WriteCanonicalSummary$stream = defineFunction("user.WriteCanonicalSummary$stream", "sync", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => ai.stream.Stream<CanonicalSummary$stream | null, CanonicalSummary>;

/**
 * Analysis, not reproduction (law 4).
 * 
 * The prompt asks for claims, arguments and consequences a reader can act on --
 * never a condensed retelling that could stand in for the original. See
 * docs/content-policy.md.
 */
export const WriteCanonicalSummary$stream_async = defineFunction("user.WriteCanonicalSummary$stream", "async", ["workTitle", "kind", "context"]) as (workTitle: string, kind: string, context: string, $opts?: { $ctx?: BamlCallContext | undefined } | undefined) => Promise<ai.stream.Stream<CanonicalSummary$stream | null, CanonicalSummary>>;
