/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  CanonicalSummary,  Pull,  RecallQuestion,  TopicSlug } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface CanonicalSummary {
      title?: string | null
      elevatorPitch?: string | null
      whyItMatters?: string | null
      pulls: Pull[]
      topics: types.TopicSlug[]
    }
    /**
     * One atomic idea that stands on its own out of context, structured for progressive depth.
    */
    export interface Pull {
      /**
       * Shortest stop: states the idea rather than teasing it.
       */
      headline?: string | null
      body?: string | null
      whyItMatters?: string | null
      example?: string | null
      explanation?: string | null
      question?: RecallQuestion | null
    }
    /**
     * One recall question, produced by the same call that produced the idea.
 * 
 * `distractors` are what turn the recall interrupt from a self-graded reveal
 * into something that can be wrong — and grading three wrong answers against
 * one right one is a comparison the client does, so no model goes near the
 * read path.
    */
    export interface RecallQuestion {
      prompt?: string | null
      answer?: string | null
      distractors: string[]
    }
}