/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
/**
 * Every `topics.slug` a generated work may be filed under.
 * 
 * Mirrors `TOPIC_SLUGS` in `supabase/functions/_shared/providers.ts`, which in
 * turn mirrors the taxonomy seeded by `20260831025500_topics_with_something_behind_them`.
 * An enum rather than a string: a slug outside the list is rejected at the
 * boundary instead of being discovered by `upsertWork`, which silently drops
 * what it cannot look up. If the taxonomy migration changes, this changes in
 * the same commit.
 */
export enum TopicSlug {
  Philosophy = "Philosophy",
  Ethics = "Ethics",
  Stoicism = "Stoicism",
  Logic = "Logic",
  Metaphysics = "Metaphysics",
  Aesthetics = "Aesthetics",
  Psychology = "Psychology",
  Attention = "Attention",
  Habits = "Habits",
  Learning = "Learning",
  Emotion = "Emotion",
  Science = "Science",
  Evolution = "Evolution",
  Physics = "Physics",
  Chemistry = "Chemistry",
  Astronomy = "Astronomy",
  Medicine = "Medicine",
  Society = "Society",
  Economics = "Economics",
  Liberty = "Liberty",
  Government = "Government",
  Justice = "Justice",
  Education = "Education",
  ArtsAndLetters = "ArtsAndLetters",
  Literature = "Literature",
  Rhetoric = "Rhetoric",
  Criticism = "Criticism",
  History = "History",
  Biography = "Biography",
  Revolutions = "Revolutions",
}

export interface CanonicalSummary {
  title: string
  elevatorPitch: string
  whyItMatters: string
  pulls: Pull[]
  topics: TopicSlug[]
  
}

/**
 * One atomic idea that stands on its own out of context.
 */
export interface Pull {
  /**
   * States the idea rather than teasing it.
   */
  headline: string
  body: string
  whyItMatters: string
  question?: RecallQuestion | null
  
}

/**
 * One recall question, produced by the same call that produced the idea.
 * 
 * `distractors` are what turn the recall interrupt from a self-graded reveal
 * into something that can be wrong — and grading three wrong answers against
 * one right one is a comparison the client does, so no model goes near the
 * read path.
 */
export interface RecallQuestion {
  prompt: string
  answer: string
  distractors: string[]
  
}
