#!/usr/bin/env node
/**
 * Generate packages/db/src/database.types.ts from the local Supabase stack.
 *
 * This exists rather than a bare `supabase gen types > file` redirect because
 * the committed file carries a "do not edit" header. CI checks staleness by
 * regenerating and diffing, so generation must be byte-identical every time —
 * a header added by one path and not the other makes the check fail forever.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';

const OUT = 'packages/db/src/database.types.ts';
const HEADER =
  '// Generated by `pnpm db:types` from the Supabase schema.\n' +
  '// Do not edit by hand — CI check 4 fails if this file is stale.\n\n';

const types = execFileSync('pnpm', ['exec', 'supabase', 'gen', 'types', 'typescript', '--local'], {
  encoding: 'utf8',
  maxBuffer: 32 * 1024 * 1024,
});

// The hosted generator emits an `__InternalSupabase` / `PostgrestVersion` block
// that the local CLI does not, so a file generated from the hosted project can
// never match one generated locally. Strip it in both directions: it is only a
// typing hint for a generic default, and determinism across generation sources
// is worth more than the hint.
const normalised = types.replace(
  /\n\s*\/\/ Allows to automatically instantiate[\s\S]*?__InternalSupabase: \{[\s\S]*?\n\s*\}\n/,
  '\n',
);

mkdirSync(dirname(OUT), { recursive: true });
// The CLI emits a trailing blank line; preserve it exactly.
writeFileSync(OUT, HEADER + normalised.replace(/\n*$/, '\n\n'));
console.log(`wrote ${OUT} (${types.length} chars from the schema)`);
