#!/usr/bin/env bash
#
# The laws that must not depend on anyone remembering them at 4am.
#
# Runs as a PreToolUse hook. A blocking hook takes precedence over allow rules, which is
# what makes a broad allowlist safe: an unattended run can be granted everything and still
# cannot do these four things. Permission prompts protect nobody when nobody is awake --
# this does.
#
#   1. Rewriting shared history, or `git stash`, which silently eats untracked files.
#   2. `supabase db push` -- the migration ledger has drifted; it would re-apply.
#   3. Editing a migration that is already on origin/main (law 6, append-only).
#   4. Hand-editing packages/db/src/database.types.ts (generated by `pnpm db:types`).
#
# Usage: ./scripts/guard.sh --hook   (reads the PreToolUse JSON on stdin)
# Exit: 0 allow · 2 block, with the reason on stderr.
set -uo pipefail
cd "$(git rev-parse --show-toplevel 2>/dev/null || echo .)" || exit 0

payload="$(cat)"
field() { printf '%s' "$payload" | jq -r "$1 // \"\"" 2>/dev/null; }

tool="$(field '.tool_name')"
block() { printf '%s\n' "BLOCKED — $1" "" "$2" >&2; exit 2; }

case "$tool" in
  Bash)
    cmd="$(field '.tool_input.command')"
    [ -z "$cmd" ] && exit 0

    # Match commands, not prose. A commit message or a doc edit that merely mentions a
    # force-push is not one, and blocking it would teach exactly one lesson: turn the
    # hook off. So drop heredoc bodies first, then require each pattern to sit where a
    # command actually starts.
    stripped="$(printf '%s\n' "$cmd" | awk '
      marker != "" { if ($0 == marker) marker = ""; next }
      match($0, /<<-?[[:space:]]*[\x27"]?[A-Za-z_][A-Za-z0-9_]*[\x27"]?/) {
        m = substr($0, RSTART, RLENGTH)
        gsub(/^<<-?[[:space:]]*|[\x27"]/, "", m)
        marker = m
      }
      { print }
    ')"
    at='(^|[;&|(]|&&|\|\||\$\()[[:space:]]*'
    at_cmd() { printf '%s' "$stripped" | grep -qE "${at}$1"; }

    if at_cmd 'git[[:space:]]+push([[:space:]]+[^;&|]*)?[[:space:]]+(--force-with-lease|--force|-f)([[:space:]]|=|$)'; then
      block "history rewrite on a shared branch." \
"A merge commit keeps every other checkout valid; a force-push does not. If the branch is
yours alone and the rewrite is genuinely intended, do it yourself outside this session."
    fi
    if at_cmd 'git[[:space:]]+filter-branch([[:space:]]|$)'; then
      block "history rewrite on a shared branch." \
"That command rewrites every commit it touches. Nothing in an unattended run needs it."
    fi
    if at_cmd 'git[[:space:]]+stash([[:space:]]|$)'; then
      block "\`git stash\` is off during unattended work." \
"With -u it takes untracked files with it, and a later \`stash drop\` deletes them with no
reflog to recover from. Commit to a scratch branch instead — that is recoverable."
    fi
    if at_cmd '(pnpm[[:space:]]+exec[[:space:]]+|npx[[:space:]]+)?supabase[[:space:]]+db[[:space:]]+push([[:space:]]|$)'; then
      block "\`supabase db push\` is never correct in this repo." \
"Production applied the last migrations under MCP-minted version strings, so the ledger
does not match the repo filenames. A push would re-apply them. Use
mcp__Supabase__apply_migration, and read .claude/skills/migration/SKILL.md."
    fi
    ;;
  Edit|Write|NotebookEdit)
    path="$(field '.tool_input.file_path')"
    [ -z "$path" ] && exit 0
    rel="${path#"$PWD"/}"
    case "$rel" in
      packages/db/src/database.types.ts)
        block "packages/db/src/database.types.ts is generated." \
"Hand-editing it makes CI check 4 fail on the staleness diff. Run \`pnpm db:types\` and
commit the result." ;;
      supabase/migrations/*)
        if git cat-file -e "origin/main:$rel" 2>/dev/null; then
          block "$rel is already on origin/main (law 6: migrations are append-only)." \
"Editing it silently diverges every environment that has already applied it. Add a new
migration that supersedes it — \`/migrate <short_name>\`."
        fi ;;
    esac
    ;;
esac
exit 0
