#!/usr/bin/env node
/**
 * Turn the public-domain manifest into generation jobs.
 *
 *   node scripts/seed-corpus.mjs --check              validate every URL, write nothing
 *   node scripts/seed-corpus.mjs --sql --limit 5      emit SQL for the first five
 *   node scripts/seed-corpus.mjs --sql --skip 5       emit SQL for everything after them
 *
 * **This script never touches the database, and holds no credential.** It validates and
 * prints SQL; something with service-role access runs it. That is not squeamishness —
 * seeding needs service_role, law 7 says that key lives only where the platform injects
 * it, and a script that wanted it locally would be an argument for putting it there.
 *
 * It also does not go through `enqueue_generation_job`. That RPC derives its requester
 * from `auth.uid()` and enforces a per-reader daily quota — 3 fast, 50 hard ceiling —
 * which is the right rule for a reader asking for a summary and the wrong one for an
 * operator seeding a library. The SQL mirrors what the RPC does (insert, then send in
 * the same statement) without the quota.
 *
 *   ┌── manifest ──┐   --check    ┌── fetch each URL ──┐
 *   │ 61 sources   │ ──────────→  │ status · bytes     │ → report, exit non-zero on any failure
 *   └──────────────┘              └────────────────────┘
 *          │         --sql
 *          └──────────────────→   INSERT generation_jobs + pgmq.send  → stdout
 *
 * Re-running is safe. `works.content_hash` carries a partial unique index and
 * `acquire` asks `findPublishedSummaryByHash` before calling any provider, so a source
 * already summarised is adopted rather than regenerated: the second run costs nothing.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(HERE, 'corpus', 'public-domain.json');

/** Matches MAX_SOURCE_CHARS in `_shared/source.ts`. Past this, `acquire` truncates. */
const MAX_SOURCE_CHARS = 200_000;
/** Below this, `acquire` refuses: too little text to be worth summarising. */
const MIN_SOURCE_CHARS = 200;

const args = process.argv.slice(2);
const has = (flag) => args.includes(flag);
const valueOf = (flag, fallback) => {
  const i = args.indexOf(flag);
  return i === -1 ? fallback : Number(args[i + 1]);
};

const { sources } = JSON.parse(readFileSync(MANIFEST, 'utf8'));
const selected = sources.slice(
  valueOf('--skip', 0),
  valueOf('--skip', 0) + valueOf('--limit', sources.length),
);

/** Rough stand-in for `extractText`, good enough to judge whether a page has prose. */
function visibleTextLength(html) {
  return html
    .replace(/<script[\s\S]*?<\/script>/gi, ' ')
    .replace(/<style[\s\S]*?<\/style>/gi, ' ')
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim().length;
}

async function check() {
  let failures = 0;

  for (const source of selected) {
    let line;
    try {
      const response = await fetch(source.url, {
        headers: { accept: 'text/html' },
        signal: AbortSignal.timeout(20_000),
      });

      if (!response.ok) {
        failures += 1;
        line = `FAIL ${String(response.status).padEnd(4)}`;
      } else {
        const chars = visibleTextLength(await response.text());
        // A 404 on Wikisource still returns 200 with a "no text" stub, so status
        // alone proves nothing. Length is what distinguishes a page from a stub.
        if (chars < MIN_SOURCE_CHARS) {
          failures += 1;
          line = `EMPTY ${String(chars).padStart(6)}c`;
        } else if (chars > MAX_SOURCE_CHARS) {
          // Not a failure: `acquire` truncates and records that it did. Worth
          // seeing, because a truncated source is summarised from its opening only.
          line = `LONG  ${String(chars).padStart(6)}c`;
        } else {
          line = `ok    ${String(chars).padStart(6)}c`;
        }
      }
    } catch (e) {
      failures += 1;
      line = `ERROR ${e instanceof Error ? e.name : 'unknown'}`;
    }

    console.log(`${line}  ${source.title}`);
  }

  console.log(`\n${selected.length - failures}/${selected.length} usable`);
  if (failures) {
    console.log('Fix or remove the failures before seeding — a bad URL is a job that');
    console.log('burns three retries and fails with nothing to show for it.');
    process.exitCode = 1;
  }
}

/** Single-quote escaping for SQL literals. The manifest is committed, but titles have apostrophes. */
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;

function sql() {
  console.log('-- Generated by scripts/seed-corpus.mjs. Run as service_role.');
  console.log('--');
  console.log('-- Mirrors enqueue_generation_job without its per-reader quota: insert and');
  console.log('-- send share one statement, so a job either exists and is queued or neither.');
  console.log('-- visibility=public and rights_status=public_domain are what let the result');
  console.log('-- clear resolve_identity and moderate, and reach the feed.');
  console.log('');
  console.log('with reader as (select id from auth.users order by created_at limit 1),');
  console.log('     target(title, kind, url) as (values');

  console.log(
    selected.map((s) => `       (${lit(s.title)}, ${lit(s.kind)}, ${lit(s.url)})`).join(',\n'),
  );

  console.log('     ),');
  console.log('     queued as (');
  console.log(
    '       insert into public.generation_jobs (requester_id, target, status, visibility)',
  );
  console.log('       select reader.id,');
  console.log('              jsonb_build_object(');
  console.log("                'title', target.title,");
  console.log("                'kind', target.kind,");
  console.log("                'url', target.url,");
  console.log("                'rights_status', 'public_domain'");
  console.log('              ),');
  console.log("              'queued', 'public'");
  console.log('       from target, reader');
  console.log('       returning id');
  console.log('     )');
  console.log('select count(*) as queued,');
  console.log('       count(pgmq.send(');
  console.log("         'generation',");
  console.log("         jsonb_build_object('jobId', queued.id, 'step', 'resolve_identity'),");
  console.log('         0');
  console.log('       )) as sent');
  console.log('from queued;');
}

if (has('--check')) await check();
else if (has('--sql')) sql();
else {
  console.log('Usage: seed-corpus.mjs (--check | --sql) [--limit N] [--skip N]');
  process.exitCode = 2;
}
