-- Pulls: original commentary, with concept-axis embeddings so the Delta works.
--
-- Note the deliberate near-duplicate: Epictetus and Marcus Aurelius each get a
-- "your judgement, not the event, is what wounds you" card. They share the same
-- axes, so the Delta will treat the second as already-known once the first is
-- learned — which is exactly the behaviour the mechanic exists to demonstrate.

insert into public.pulls (summary_id, ordinal, headline, body, explanation,
                          why_it_matters, example, estimated_read_seconds, embedding)
select s.id, v.ordinal, v.headline, v.body, v.explanation, v.why, v.example,
       v.secs, public.synthetic_embedding(v.axes::jsonb)
from (values
  -- The Enchiridion
  ('the-enchiridion', 1, 'Some things are up to you. Most are not.',
   'Your judgements, intentions and effort are yours. Reputation, outcomes, other people and the past are not.',
   'The distinction is not a comfort but a filter. Effort spent on the second category is spent at a loss, however sincerely it is spent.',
   'Almost every practical philosophy since is a variation on where exactly this line falls.',
   'You can control how thoroughly you prepare. You cannot control whether the panel likes you.',
   28, '{"control":1.0,"stoicism":0.6}'),
  ('the-enchiridion', 2, 'You are disturbed by your judgement, not by the event.',
   'Events arrive without commentary. The distress comes from the verdict you attach to them, which is why two people meet the same news very differently.',
   'This is not a claim that feelings are optional. It is a claim about where the leverage is: the verdict is nearer to hand than the event.',
   'It is the direct ancestor of cognitive behavioural therapy, which industrialised exactly this move.',
   'The delayed train is a fact. "This always happens to me" is the part doing the damage.',
   32, '{"judgement":1.0,"stoicism":0.5}'),
  ('the-enchiridion', 3, 'Wanting the world to be otherwise is a guaranteed loss.',
   'Demanding that events conform to your preferences sets up a contest you cannot win. Wanting them as they are ends the contest without surrender.',
   'The move is not passivity. It is refusing to make your composure conditional on things that were never going to consult you.',
   'It separates acceptance from resignation — a distinction most self-help collapses.',
   null, 26, '{"acceptance":1.0,"stoicism":0.5}'),
  ('the-enchiridion', 4, 'Rehearse the difficulty before it arrives.',
   'Imagine the loss, the delay, the refusal, in advance and in detail. Not to be gloomy, but so the event arrives already familiar.',
   'Surprise does much of the damage in a setback. Rehearsal removes the surprise while the stakes are still zero.',
   'It is the same logic as a fire drill, applied to the inside of a life.',
   'Before the trip: the flight is cancelled. Now what? Answer it now, cheaply.',
   30, '{"preparation":1.0,"stoicism":0.4}'),

  -- Meditations
  ('meditations', 1, 'What blocks the way becomes the way.',
   'An obstruction is not only an interruption of the work. It is often the material the work is now made of.',
   'The reframe is narrow and worth keeping narrow: the obstacle is not secretly good, but it is the actual situation, and the actual situation is the only one you can act in.',
   'It converts a complaint into a next action, which is the only useful thing a complaint can become.',
   'The collaborator drops out. The project is now a study in doing it alone.',
   30, '{"obstacle":1.0,"stoicism":0.5}'),
  ('meditations', 2, 'It is your opinion of the thing that wounds you, and you can revoke it.',
   'The pain is attached to the verdict rather than the event, and the verdict is something you issued and can withdraw.',
   'Written by someone with unlimited power over external events, who concluded the leverage was still internal. That provenance is part of the argument.',
   'Notice this is the same claim Epictetus makes. Marcus had read him — the idea has a lineage, not two inventors.',
   null, 30, '{"judgement":1.0,"stoicism":0.5}'),
  ('meditations', 3, 'You could leave life right now. Let that decide what you do next.',
   'Mortality is used here as a scheduling constraint rather than a source of dread: it settles what is worth the remaining time.',
   'The purpose is editorial. Most of what occupies a day survives this test poorly, and is meant not to.',
   'It is the most reliable known method for shortening a list of priorities.',
   null, 28, '{"mortality":1.0,"stoicism":0.5}'),
  ('meditations', 4, 'Do the work in front of you, without an audience in your head.',
   'The task does not require narration, an imagined observer, or a running commentary on how well you are doing it.',
   'Much of the effort in any job goes into performing the job to a spectator who is not there. Removing them returns the effort.',
   'It is a direct attack on the part of work that is really self-presentation.',
   null, 26, '{"duty":1.0,"stoicism":0.4}'),

  -- On Liberty
  ('on-liberty', 1, 'Silencing an opinion robs the people doing the silencing.',
   'If the opinion is right, they lose a correction. If it is wrong, they lose the sharper understanding that comes from defeating it.',
   'The argument is deliberately built to survive the case where the suppressed view is false — which is where every real test of it happens.',
   'It moves free expression from a favour granted to speakers into a requirement for the listeners to think well.',
   null, 32, '{"dissent":1.0,"liberty":0.5}'),
  ('on-liberty', 2, 'Power over another is only legitimate to prevent harm to others.',
   'Their own good — physical or moral — is not a sufficient warrant for compulsion. It is a reason to persuade, not to coerce.',
   'The whole difficulty sits in the word "harm", and Mill knows it. The principle is a place to start the argument, not a way to end it.',
   'Nearly every modern dispute about regulation is a dispute about where this line falls.',
   null, 34, '{"harm":1.0,"liberty":0.6}'),
  ('on-liberty', 3, 'An unchallenged truth decays into a dead dogma.',
   'A belief that is never contested is still held, but it stops being understood. The holder keeps the conclusion and loses the reasons.',
   'This is why Mill wants opposition even to things he considers settled: the challenge is what keeps a true belief alive as knowledge.',
   'It explains why people who agree with you for bad reasons are not much use.',
   'Ask someone certain of a position to state the strongest case against it. Often there is nothing there.',
   34, '{"dogma":1.0,"dissent":0.8}'),
  ('on-liberty', 4, 'Social pressure can coerce more effectively than law.',
   'Custom, disapproval and the fear of standing out reach places legislation never gets to, and leave no record.',
   'Mill treats conformity as a governing force in its own right — one with no constitution, no appeal, and no visible enforcement.',
   'It is the part of the book that reads as though it were written about the internet.',
   null, 30, '{"conformity":1.0,"liberty":0.5}'),

  -- Walden
  ('walden', 1, 'The cost of a thing is the amount of life you exchange for it.',
   'Not the price. The hours required to earn the price, plus the hours spent maintaining, storing and worrying about what you bought.',
   'It is a genuine accounting method, not a metaphor. Run it on a large purchase and the number is usually uncomfortable.',
   'It converts every spending decision into a question about time, which is the resource actually in short supply.',
   'A thing costing a week''s wages costs a week of life, and the week does not come back.',
   32, '{"simplicity":1.0,"economics":0.4}'),
  ('walden', 2, 'Most luxuries are hindrances wearing a disguise.',
   'Many comforts add maintenance, obligation and anxiety in quantities that exceed the comfort they deliver.',
   'The test is not whether something is pleasant but whether it is net-positive once its upkeep is counted. A surprising amount is not.',
   'It is the argument underneath every later minimalism, stated more sharply than most of them manage.',
   null, 28, '{"consumption":1.0,"simplicity":0.9}'),
  ('walden', 3, 'Living deliberately is mostly deciding what to attend to.',
   'The point of the experiment was not the cabin. It was removing enough noise to find out which parts of a life were actually chosen.',
   'Attention is treated as the scarce resource and the real unit of a life — long before anyone was competing for it professionally.',
   'It reframes simplicity as an attention strategy rather than an aesthetic.',
   null, 30, '{"attention":1.0,"simplicity":0.5}'),

  -- Origin of Species
  ('on-the-origin-of-species', 1, 'Three conditions are enough: variation, heredity, and differential survival.',
   'If individuals differ, if some of that difference is inherited, and if it affects survival or reproduction, then the population must change. No further mechanism is needed.',
   'The force of the argument is its poverty. It assumes almost nothing, and what it assumes is observable.',
   'It is the rare idea whose logical core fits in one sentence and still reorganised an entire science.',
   null, 36, '{"evolution":1.0,"mechanism":0.5}'),
  ('on-the-origin-of-species', 2, 'Very small advantages, compounded over deep time, do very large work.',
   'A trait that helps fractionally, in each generation, across an interval of time the mind is not built to picture, produces results that look designed.',
   'The intuition that fails here is not biological but arithmetic: humans reliably underestimate compounding, and geological time is compounding''s best case.',
   'The same failure of intuition explains why people misjudge interest, habits, and epidemics.',
   null, 34, '{"compounding":1.0,"evolution":0.6}'),
  ('on-the-origin-of-species', 3, 'Common descent explains why life falls into nested groups.',
   'Species sort into groups within groups — a pattern you would expect from branching ancestry, and would have no reason to expect otherwise.',
   'This is the evidential half of the book, and it does work the mechanism alone cannot: it explains a pattern that was already catalogued and unexplained.',
   'A theory that explains an existing puzzle is stronger than one that merely accommodates it.',
   null, 32, '{"descent":1.0,"evolution":0.8}'),

  -- Relativity
  ('relativity', 1, 'If light''s speed is the same for everyone, simultaneity cannot be.',
   'Two events that occur at the same moment for one observer occur at different moments for another moving relative to the first. Both are right.',
   'This is a conclusion, not an assumption. Hold the speed of light fixed for all observers and the shared "now" is what has to give way.',
   'It is the cleanest demonstration that an intuition can be universal, confident, and wrong.',
   null, 38, '{"relativity":1.0,"physics":0.5}'),
  ('relativity', 2, 'Standing on the ground and accelerating in space feel identical.',
   'Inside a sealed box there is no local experiment that distinguishes resting in a gravitational field from accelerating in empty space.',
   'From that equivalence follows the reinterpretation of gravity as the geometry of spacetime rather than a force acting across it.',
   'A thought experiment requiring no apparatus produced the general theory.',
   null, 36, '{"equivalence":1.0,"physics":0.5}'),
  ('relativity', 3, 'The laws should look the same to every unaccelerated observer.',
   'No inertial frame is privileged. There is no state of rest that the universe regards as the real one.',
   'This is a demand for consistency rather than a discovery about matter — and taken seriously, it forces everything else.',
   'It shows how much can follow from insisting a theory not play favourites.',
   null, 34, '{"invariance":1.0,"physics":0.6}')
) as v(work, ordinal, headline, body, explanation, why, example, secs, axes)
join public.works w on w.slug = v.work
join public.summaries s on s.work_id = w.id and s.version = 1;
