with target(title, kind, url, author) as (values
       ('Self-Reliance', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Self-Reliance', 'Ralph Waldo Emerson'),
       ('Compensation', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Compensation', 'Ralph Waldo Emerson'),
       ('Circles', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Circles', 'Ralph Waldo Emerson'),
       ('The Over-Soul', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/The_Over-Soul', 'Ralph Waldo Emerson'),
       ('Civil Disobedience', 'essay', 'https://en.wikisource.org/wiki/Civil_Disobedience_(Thoreau)', 'Henry David Thoreau'),
       ('Life Without Principle', 'essay', 'https://en.wikisource.org/wiki/Life_Without_Principle', 'Henry David Thoreau'),
       ('Of Studies', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Studies', 'Francis Bacon'),
       ('Of Truth', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Truth', 'Francis Bacon'),
       ('Of Innovations', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Innovations', 'Francis Bacon'),
       ('Of Great Place', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Great_Place', 'Francis Bacon'),
       ('Of Cannibals', 'essay', 'https://en.wikisource.org/wiki/The_Essays_of_Montaigne/Book_I/Chapter_XXX', 'Michel de Montaigne'),
       ('Of the Education of Children', 'essay', 'https://en.wikisource.org/wiki/The_Essays_of_Montaigne/Book_I/Chapter_XXV', 'Michel de Montaigne'),
       ('Federalist No. 1: General Introduction', 'essay', 'https://en.wikisource.org/wiki/The_Federalist_Papers/No._1', 'Alexander Hamilton'),
       ('Federalist No. 10: The Union as a Safeguard Against Faction', 'essay', 'https://en.wikisource.org/wiki/The_Federalist_Papers/No._10', 'James Madison'),
       ('Federalist No. 51: The Structure of the Government', 'essay', 'https://en.wikisource.org/wiki/The_Federalist_Papers/No._51', 'James Madison'),
       ('Federalist No. 78: The Judiciary Department', 'essay', 'https://en.wikisource.org/wiki/The_Federalist_Papers/No._78', 'Alexander Hamilton'),
       ('The Gettysburg Address', 'lecture', 'https://en.wikisource.org/wiki/Gettysburg_Address', 'Abraham Lincoln'),
       ('Second Inaugural Address', 'lecture', 'https://en.wikisource.org/wiki/Abraham_Lincoln%27s_Second_Inaugural_Address', 'Abraham Lincoln'),
       ('What to the Slave is the Fourth of July?', 'lecture', 'https://en.wikisource.org/wiki/What_to_the_Slave_Is_the_Fourth_of_July%3F', 'Frederick Douglass'),
       ('Ain''t I a Woman?', 'lecture', 'https://en.wikisource.org/wiki/Ain%27t_I_a_Woman%3F', 'Sojourner Truth'),
       ('A Vindication of the Rights of Woman: Introduction', 'essay', 'https://en.wikisource.org/wiki/A_Vindication_of_the_Rights_of_Woman/Introduction', 'Mary Wollstonecraft'),
       ('Common Sense', 'essay', 'https://en.wikisource.org/wiki/Common_Sense_(1776)/Common_Sense', 'Thomas Paine'),
       ('The Subjection of Women: Chapter I', 'essay', 'https://en.wikisource.org/wiki/The_Subjection_of_Women/Chapter_1', 'John Stuart Mill'),
       ('The Wealth of Nations: Of the Division of Labour', 'essay', 'https://en.wikisource.org/wiki/The_Wealth_of_Nations/Book_I/Chapter_1', 'Adam Smith'),
       ('The Wealth of Nations: Of the Principle which gives Occasion to the Division of Labour', 'essay', 'https://en.wikisource.org/wiki/The_Wealth_of_Nations/Book_I/Chapter_2', 'Adam Smith'),
       ('The Theory of the Leisure Class: Conspicuous Consumption', 'essay', 'https://en.wikisource.org/wiki/The_Theory_of_the_Leisure_Class/Chapter_4', 'Thorstein Veblen'),
       ('On the Origin of Species: Struggle for Existence', 'paper', 'https://en.wikisource.org/wiki/On_the_Origin_of_Species_(1859)/Chapter_III', 'Charles Darwin'),
       ('On the Origin of Species: Natural Selection', 'paper', 'https://en.wikisource.org/wiki/On_the_Origin_of_Species_(1859)/Chapter_IV', 'Charles Darwin'),
       ('On the Origin of Species: Difficulties on Theory', 'paper', 'https://en.wikisource.org/wiki/On_the_Origin_of_Species_(1859)/Chapter_VI', 'Charles Darwin'),
       ('The Chemical History of a Candle: Lecture I', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_I', 'Michael Faraday'),
       ('The Will to Believe', 'lecture', 'https://en.wikisource.org/wiki/The_Will_to_Believe', 'William James'),
       ('What Pragmatism Means', 'lecture', 'https://en.wikisource.org/wiki/Pragmatism:_A_New_Name_for_Some_Old_Ways_of_Thinking/Lecture_II', 'William James'),
       ('The Souls of Black Folk: Of Our Spiritual Strivings', 'essay', 'https://en.wikisource.org/wiki/The_Souls_of_Black_Folk/Chapter_1', 'W. E. B. Du Bois'),
       ('The Souls of Black Folk: Of Mr. Booker T. Washington and Others', 'essay', 'https://en.wikisource.org/wiki/The_Souls_of_Black_Folk/Chapter_3', 'W. E. B. Du Bois'),
       ('The Prince: Concerning New Principalities', 'book', 'https://en.wikisource.org/wiki/The_Prince_(Marriott)/Chapter_6', 'Niccolò Machiavelli'),
       ('The Poetic Principle', 'essay', 'https://en.wikisource.org/wiki/The_Poetic_Principle', 'Edgar Allan Poe'),
       ('The Philosophy of Composition', 'essay', 'https://en.wikisource.org/wiki/The_Philosophy_of_Composition', 'Edgar Allan Poe'),
       ('The Decay of Lying', 'essay', 'https://en.wikisource.org/wiki/Intentions/The_Decay_of_Lying', 'Oscar Wilde'),
       ('Apology', 'book', 'https://classics.mit.edu/Plato/apology.html', 'Plato'),
       ('Crito', 'book', 'https://classics.mit.edu/Plato/crito.html', 'Plato'),
       ('Meno', 'book', 'https://classics.mit.edu/Plato/meno.html', 'Plato'),
       ('Phaedo', 'book', 'https://classics.mit.edu/Plato/phaedo.html', 'Plato'),
       ('Symposium', 'book', 'https://classics.mit.edu/Plato/symposium.html', 'Plato'),
       ('Gorgias', 'book', 'https://classics.mit.edu/Plato/gorgias.html', 'Plato'),
       ('The Republic, Book II', 'book', 'https://classics.mit.edu/Plato/republic.2.i.html', 'Plato'),
       ('Poetics', 'book', 'https://classics.mit.edu/Aristotle/poetics.1.1.html', 'Aristotle'),
       ('Rhetoric, Book I', 'book', 'https://classics.mit.edu/Aristotle/rhetoric.1.i.html', 'Aristotle'),
       ('Metaphysics, Book I', 'book', 'https://classics.mit.edu/Aristotle/metaphysics.1.i.html', 'Aristotle'),
       ('Nicomachean Ethics, Book I', 'book', 'https://classics.mit.edu/Aristotle/nicomachaen.1.i.html', 'Aristotle'),
       ('Nicomachean Ethics, Book II', 'book', 'https://classics.mit.edu/Aristotle/nicomachaen.2.ii.html', 'Aristotle'),
       ('On the Soul, Book I', 'book', 'https://classics.mit.edu/Aristotle/soul.1.i.html', 'Aristotle'),
       ('The Discourses, Book I', 'book', 'https://classics.mit.edu/Epictetus/discourses.1.one.html', 'Epictetus'),
       ('Aphorisms', 'book', 'https://classics.mit.edu/Hippocrates/aphorisms.1.i.html', 'Hippocrates'),
       ('History of the Peloponnesian War, Book II', 'book', 'https://classics.mit.edu/Thucydides/pelopwar.2.second.html', 'Thucydides'),
       ('Discourse on the Method', 'essay', 'https://www.gutenberg.org/cache/epub/59/pg59.txt', 'Rene Descartes'),
       ('Caesar', 'book', 'https://classics.mit.edu/Plutarch/caesar.html', 'Plutarch'),
       ('Alexander', 'book', 'https://classics.mit.edu/Plutarch/alexandr.html', 'Plutarch'),
       ('Lycurgus', 'book', 'https://classics.mit.edu/Plutarch/lycurgus.html', 'Plutarch'),
       ('Solon', 'book', 'https://classics.mit.edu/Plutarch/solon.html', 'Plutarch'),
       ('On the Sacred Disease', 'book', 'https://classics.mit.edu/Hippocrates/sacred.html', 'Hippocrates'),
       ('On the Heavens, Book I', 'book', 'https://classics.mit.edu/Aristotle/heavens.1.i.html', 'Aristotle'),
       ('Physics, Book I', 'book', 'https://classics.mit.edu/Aristotle/physics.1.i.html', 'Aristotle'),
       ('Prior Analytics, Book I', 'book', 'https://classics.mit.edu/Aristotle/prior.1.i.html', 'Aristotle'),
       ('Posterior Analytics, Book I', 'book', 'https://classics.mit.edu/Aristotle/posterior.1.i.html', 'Aristotle'),
       ('Topics, Book I', 'book', 'https://classics.mit.edu/Aristotle/topics.1.i.html', 'Aristotle'),
       ('On Sophistical Refutations', 'book', 'https://classics.mit.edu/Aristotle/sophist_refut.1.1.html', 'Aristotle'),
       ('Pericles', 'book', 'https://classics.mit.edu/Plutarch/pericles.html', 'Plutarch'),
       ('Cicero', 'book', 'https://classics.mit.edu/Plutarch/cicero.html', 'Plutarch'),
       ('Demosthenes', 'book', 'https://classics.mit.edu/Plutarch/demosthe.html', 'Plutarch'),
       ('Theseus', 'book', 'https://classics.mit.edu/Plutarch/theseus.html', 'Plutarch'),
       ('Coriolanus', 'book', 'https://classics.mit.edu/Plutarch/coriolan.html', 'Plutarch'),
       ('Cato the Younger', 'book', 'https://classics.mit.edu/Plutarch/cato_you.html', 'Plutarch'),
       ('Antony', 'book', 'https://classics.mit.edu/Plutarch/antony.html', 'Plutarch'),
       ('Pyrrhus', 'book', 'https://classics.mit.edu/Plutarch/pyrrhus.html', 'Plutarch'),
       ('On Memory and Reminiscence', 'book', 'https://classics.mit.edu/Aristotle/memory.html', 'Aristotle'),
       ('On Dreams', 'book', 'https://classics.mit.edu/Aristotle/dreams.html', 'Aristotle'),
       ('On Sleep and Sleeplessness', 'book', 'https://classics.mit.edu/Aristotle/sleep.html', 'Aristotle'),
       ('On Prophesying by Dreams', 'book', 'https://classics.mit.edu/Aristotle/prophesying.html', 'Aristotle'),
       ('On the Heavens, Book II', 'book', 'https://classics.mit.edu/Aristotle/heavens.2.ii.html', 'Aristotle'),
       ('Meteorology, Book I', 'book', 'https://classics.mit.edu/Aristotle/meteorology.1.i.html', 'Aristotle'),
       ('On Generation and Corruption, Book I', 'book', 'https://classics.mit.edu/Aristotle/gener_corr.1.i.html', 'Aristotle'),
       ('On the Motion of Animals', 'book', 'https://classics.mit.edu/Aristotle/motion_animals.html', 'Aristotle'),
       ('On the Gait of Animals', 'book', 'https://classics.mit.edu/Aristotle/gait_anim.html', 'Aristotle'),
       ('The Chemical History of a Candle: Lecture II', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_II', 'Michael Faraday'),
       ('The Chemical History of a Candle: Lecture III', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_III', 'Michael Faraday'),
       ('The Chemical History of a Candle: Lecture IV', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_IV', 'Michael Faraday'),
       ('The Chemical History of a Candle: Lecture V', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_V', 'Michael Faraday'),
       ('The Chemical History of a Candle: Lecture VI', 'lecture', 'https://en.wikisource.org/wiki/The_Chemical_History_of_a_Candle/Lecture_VI', 'Michael Faraday'),
       ('The Critic as Artist', 'essay', 'https://en.wikisource.org/wiki/Intentions/The_Critic_as_Artist', 'Oscar Wilde'),
       ('The Poet', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/The_Poet', 'Ralph Waldo Emerson'),
       ('Art', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Art', 'Ralph Waldo Emerson'),
       ('Experience', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Experience', 'Ralph Waldo Emerson'),
       ('Love', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Love', 'Ralph Waldo Emerson'),
       ('Friendship', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Friendship', 'Ralph Waldo Emerson'),
       ('Heroism', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Heroism', 'Ralph Waldo Emerson'),
       ('Prudence', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Prudence', 'Ralph Waldo Emerson'),
       ('Intellect', 'essay', 'https://en.wikisource.org/wiki/Essays:_First_Series/Intellect', 'Ralph Waldo Emerson'),
       ('Of Death', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Death', 'Francis Bacon'),
       ('Manifesto of the Communist Party', 'essay', 'https://en.wikisource.org/wiki/Manifesto_of_the_Communist_Party', 'Karl Marx and Friedrich Engels'),
       ('The Subjection of Women: Chapter II', 'essay', 'https://en.wikisource.org/wiki/The_Subjection_of_Women/Chapter_2', 'John Stuart Mill'),
       ('The Souls of Black Folk: Of the Meaning of Progress', 'essay', 'https://en.wikisource.org/wiki/The_Souls_of_Black_Folk_(2nd_ed)/Chapter_4', 'W. E. B. Du Bois'),
       ('What the Tortoise Said to Achilles', 'essay', 'https://en.wikisource.org/wiki/What_the_Tortoise_Said_to_Achilles', 'Lewis Carroll'),
       ('Sketch of the Analytical Engine: Notes by the Translator', 'paper', 'https://en.wikisource.org/wiki/Scientific_Memoirs/3/Sketch_of_the_Analytical_Engine_invented_by_Charles_Babbage,_Esq./Notes_by_the_Translator', 'Ada Lovelace'),
       ('The Ethics of Belief', 'essay', 'https://en.wikisource.org/wiki/The_Ethics_of_Belief', 'William Kingdon Clifford'),
       ('The Problems of Philosophy: On Induction', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_6', 'Bertrand Russell'),
       ('The Problems of Philosophy: The Value of Philosophy', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_15', 'Bertrand Russell'),
       ('The Problems of Philosophy: Appearance and Reality', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_1', 'Bertrand Russell'),
       ('Ten Books on Architecture: Book I', 'book', 'https://en.wikisource.org/wiki/Ten_Books_on_Architecture/Book_I', 'Vitruvius'),
       ('Ten Books on Architecture: Book II', 'book', 'https://en.wikisource.org/wiki/Ten_Books_on_Architecture/Book_II', 'Vitruvius'),
       ('The Art of War', 'book', 'https://en.wikisource.org/wiki/The_Art_of_War_(Sun)', 'Sun Tzu'),
       ('Tao Te Ching', 'book', 'https://en.wikisource.org/wiki/Tao_Te_Ching_(James_Legge)', 'Laozi'),
       ('The Discourses, Book II', 'book', 'https://classics.mit.edu/Epictetus/discourses.2.two.html', 'Epictetus'),
       ('The Discourses, Book III', 'book', 'https://classics.mit.edu/Epictetus/discourses.3.three.html', 'Epictetus'),
       ('History of the Peloponnesian War, Book I', 'book', 'https://classics.mit.edu/Thucydides/pelopwar.1.first.html', 'Thucydides'),
       ('A Vindication of the Rights of Woman: Chapter II', 'essay', 'https://en.wikisource.org/wiki/A_Vindication_of_the_Rights_of_Woman/Chapter_II', 'Mary Wollstonecraft'),
       ('Democracy in America: Of Individualism in Democratic Countries', 'essay', 'https://en.wikisource.org/wiki/Democracy_in_America/Volume_2/Book_2/Chapter_2', 'Alexis de Tocqueville'),
       ('The Talented Tenth', 'essay', 'https://en.wikisource.org/wiki/The_Talented_Tenth', 'W. E. B. Du Bois'),
       ('Discourse on the Method: Part I', 'essay', 'https://en.wikisource.org/wiki/Discourse_on_the_Method/Part_1', 'René Descartes'),
       ('Discourse on the Method: Part II', 'essay', 'https://en.wikisource.org/wiki/Discourse_on_the_Method/Part_2', 'René Descartes'),
       ('Discourse on the Method: Part IV', 'essay', 'https://en.wikisource.org/wiki/Discourse_on_the_Method/Part_4', 'René Descartes'),
       ('Meditations on First Philosophy: Meditation I', 'essay', 'https://en.wikisource.org/wiki/Meditations_on_First_Philosophy/Meditation_I', 'René Descartes'),
       ('Meditations on First Philosophy: Meditation II', 'essay', 'https://en.wikisource.org/wiki/Meditations_on_First_Philosophy/Meditation_II', 'René Descartes'),
       ('Of the Standard of Taste', 'essay', 'https://en.wikisource.org/wiki/Of_the_Standard_of_Taste', 'David Hume'),
       ('What is Enlightenment?', 'essay', 'https://en.wikisource.org/wiki/What_is_Enlightenment%3F', 'Immanuel Kant'),
       ('The American Scholar', 'lecture', 'https://en.wikisource.org/wiki/The_American_Scholar', 'Ralph Waldo Emerson'),
       ('The Works of Francis Bacon: Of Simulation and Dissimulation', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Simulation_and_Dissimulation', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Envy', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Envy', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Custom and Education', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Custom_and_Education', 'Francis Bacon'),
       ('The Song Celestial (Bhagavad Gita)', 'book', 'https://en.wikisource.org/wiki/The_Song_Celestial', 'Vyasa'),
       ('Ten Books on Architecture: Book III', 'book', 'https://en.wikisource.org/wiki/Ten_Books_on_Architecture/Book_III', 'Vitruvius'),
       ('Ten Books on Architecture: Book IV', 'book', 'https://en.wikisource.org/wiki/Ten_Books_on_Architecture/Book_IV', 'Vitruvius'),
       ('Ten Books on Architecture: Book V', 'book', 'https://en.wikisource.org/wiki/Ten_Books_on_Architecture/Book_V', 'Vitruvius'),
       ('The Prince: Chapter XVII - Concerning Cruelty and Clemency', 'essay', 'https://en.wikisource.org/wiki/The_Prince_(Marriott)/Chapter_17', 'Niccolò Machiavelli'),
       ('The Prince: Chapter XVIII - In What Way Princes Must Keep Faith', 'essay', 'https://en.wikisource.org/wiki/The_Prince_(Marriott)/Chapter_18', 'Niccolò Machiavelli'),
       ('The Prince: Chapter XXV - What Fortune Can Effect in Human Affairs', 'essay', 'https://en.wikisource.org/wiki/The_Prince_(Marriott)/Chapter_25', 'Niccolò Machiavelli'),
       ('The Discourses, Book IV', 'book', 'https://classics.mit.edu/Epictetus/discourses.4.four.html', 'Epictetus'),
       ('A Defence of Poetry', 'essay', 'https://en.wikisource.org/wiki/A_Defence_of_Poetry', 'Percy Bysshe Shelley'),
       ('Democracy and Education: Chapter I', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_I', 'John Dewey'),
       ('Democracy and Education: Chapter Iv', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_IV', 'John Dewey'),
       ('Democracy and Education: Chapter Ix', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_IX', 'John Dewey'),
       ('Democracy and Education: Chapter Vii', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_VII', 'John Dewey'),
       ('Democracy and Education: Chapter Xii', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_XII', 'John Dewey'),
       ('Democracy and Education: Chapter Xiii', 'essay', 'https://en.wikisource.org/wiki/Democracy_and_Education/Chapter_XIII', 'John Dewey'),
       ('Character', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Character', 'Ralph Waldo Emerson'),
       ('Gifts', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Gifts', 'Ralph Waldo Emerson'),
       ('Manners', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Manners', 'Ralph Waldo Emerson'),
       ('Nature', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Nature', 'Ralph Waldo Emerson'),
       ('New England Reformers', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/New_England_Reformers', 'Ralph Waldo Emerson'),
       ('Nominalist and Realist', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Nominalist_and_Realist', 'Ralph Waldo Emerson'),
       ('Politics', 'essay', 'https://en.wikisource.org/wiki/Essays:_Second_Series/Politics', 'Ralph Waldo Emerson'),
       ('How We Think: What is Thought?', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_1', 'John Dewey'),
       ('How We Think: Empirical and Scientific Thinking', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_11', 'John Dewey'),
       ('How We Think: The Need for Training Thought', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_2', 'John Dewey'),
       ('How We Think: The Analysis of a Complete Act of Thought', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_6', 'John Dewey'),
       ('How We Think: Systematic Inference: Induction and Deduction', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_7', 'John Dewey'),
       ('How We Think: Judgment: The Interpretation of Facts', 'essay', 'https://en.wikisource.org/wiki/How_We_Think/Chapter_8', 'John Dewey'),
       ('Mutual Aid: A Factor of Evolution: Mutual Aid Among Animals', 'essay', 'https://en.wikisource.org/wiki/Mutual_Aid:_A_Factor_of_Evolution/Chapter_I', 'Peter Kropotkin'),
       ('Mutual Aid: A Factor of Evolution: MUTUAL AID AMONG ANIMALS (continued)', 'essay', 'https://en.wikisource.org/wiki/Mutual_Aid:_A_Factor_of_Evolution/Chapter_II', 'Peter Kropotkin'),
       ('Mutual Aid: A Factor of Evolution: Mutual Aid Amongst Ourselves', 'essay', 'https://en.wikisource.org/wiki/Mutual_Aid:_A_Factor_of_Evolution/Chapter_VII', 'Peter Kropotkin'),
       ('Mutual Aid: A Factor of Evolution: MUTUAL AID AMONGST OURSELVES (continued)', 'essay', 'https://en.wikisource.org/wiki/Mutual_Aid:_A_Factor_of_Evolution/Chapter_VIII', 'Peter Kropotkin'),
       ('Science and Hypothesis: On the Nature of Mathematical Reasoning', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_1', 'Henri Poincaré'),
       ('Science and Hypothesis: The Calculus of Probabilities', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_11', 'Henri Poincaré'),
       ('Science and Hypothesis: Mathematical Magnitude and Experiment', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_2', 'Henri Poincaré'),
       ('Science and Hypothesis: Non-Euclidean Geometries', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_3', 'Henri Poincaré'),
       ('Science and Hypothesis: Space and Geometry', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_4', 'Henri Poincaré'),
       ('Science and Hypothesis: Hypotheses in Physics', 'essay', 'https://en.wikisource.org/wiki/Science_and_Hypothesis/Chapter_9', 'Henri Poincaré'),
       ('The Conquest of Bread: Chapter I', 'essay', 'https://en.wikisource.org/wiki/The_Conquest_of_Bread/Chapter_1', 'Peter Kropotkin'),
       ('The Conquest of Bread: Chapter Xiv', 'essay', 'https://en.wikisource.org/wiki/The_Conquest_of_Bread/Chapter_14', 'Peter Kropotkin'),
       ('The Conquest of Bread: Chapter Ii', 'essay', 'https://en.wikisource.org/wiki/The_Conquest_of_Bread/Chapter_2', 'Peter Kropotkin'),
       ('The Conquest of Bread: Chapter V', 'essay', 'https://en.wikisource.org/wiki/The_Conquest_of_Bread/Chapter_5', 'Peter Kropotkin'),
       ('The Conquest of Bread: Chapter Ix', 'essay', 'https://en.wikisource.org/wiki/The_Conquest_of_Bread/Chapter_9', 'Peter Kropotkin'),
       ('The Problems of Philosophy: On Intuitive Knowledge', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_11', 'Bertrand Russell'),
       ('The Problems of Philosophy: Truth And Falsehood', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_12', 'Bertrand Russell'),
       ('The Problems of Philosophy: Knowledge, Error, And Probable Opinion', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_13', 'Bertrand Russell'),
       ('The Problems of Philosophy: The Existence Of Matter', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_2', 'Bertrand Russell'),
       ('The Problems of Philosophy: The Nature Of Matter', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_3', 'Bertrand Russell'),
       ('The Problems of Philosophy: Knowledge By Acquaintance And Knowledge By Description', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_5', 'Bertrand Russell'),
       ('The Problems of Philosophy: On Our Knowledge Of General Principles', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_7', 'Bertrand Russell'),
       ('The Problems of Philosophy: The World Of Universals', 'essay', 'https://en.wikisource.org/wiki/The_Problems_of_Philosophy/Chapter_9', 'Bertrand Russell'),
       ('The Works of Francis Bacon: Of Adversity', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Adversity', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Beauty', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Beauty', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Boldness', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Boldness', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Counsel', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Counsel', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Cunning', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Cunning', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Delays', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Delays', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Discourse', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Discourse', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Expense', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Expense', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Followers and Friends', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Followers_and_Friends', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Friendship', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Friendship', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Goodness and Goodness of Nature', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Goodness_and_Goodness_of_Nature', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Judicature', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Judicature', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Parents and Children', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Parents_and_Children', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Plantations', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Plantations', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Prophecies', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Prophecies', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Revenge', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Revenge', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Seeming Wise', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Seeming_Wise', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Travel', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Travel', 'Francis Bacon'),
       ('The Works of Francis Bacon: Of Usury', 'essay', 'https://en.wikisource.org/wiki/The_Works_of_Francis_Bacon/Volume_1/Essays/Of_Usury', 'Francis Bacon')
     ),
     -- Only what is genuinely missing.
     --
     -- Without this the statement enqueues every entry in the manifest every
     -- time it runs, including the ones already published — duplicate works in
     -- the feed and duplicate model spend, which is the one cost law 2 is
     -- written to avoid. Re-running a seeder is the normal way to add a source,
     -- so it has to be safe to do.
     --
     -- Matched on lower(title) because that is what the manifest guarantees is
     -- unique. A URL match would miss the same work reached by two hosts, which
     -- has already happened once here: Common Sense arrived from Wikisource and
     -- Gutenberg and was published twice.
     missing as (
       select t.* from target t
       where not exists (
         select 1 from public.works w
         join public.summaries s on s.work_id = w.id
         where lower(w.title) = lower(t.title)
           and s.status = 'published' and s.visibility = 'public'
           and w.rights_status in ('public_domain', 'licensed')
       )
       and not exists (
         select 1 from public.generation_jobs g
         where lower(g.target->>'title') = lower(t.title)
           and g.status in ('queued', 'running')
       )
     ),
     queued as (
       insert into public.generation_jobs (requester_id, target, status, visibility)
       select null,
              jsonb_build_object(
                'title', missing.title,
                'kind', missing.kind,
                'url', missing.url,
                'author', nullif(missing.author, ''),
                'rights_status', 'public_domain'
              ),
              'queued', 'public'
       from missing
       returning id
     ),
     -- LATERAL, not count(pgmq.send(...)). `send` returns SETOF bigint, and
     -- Postgres has rejected set-returning functions inside aggregate arguments
     -- since v10 — so the aggregate form fails at parse analysis and inserts
     -- nothing. Every migration reaches pgmq through `perform`, which discards
     -- a result set; count() cannot. This is the shape that runs.
     sent as (
       select s.msg_id
       from queued q
       cross join lateral pgmq.send(
         'generation',
         jsonb_build_object('jobId', q.id, 'step', 'resolve_identity'),
         0
       ) as s(msg_id)
     )
-- One count, not two: a data-modifying CTE is materialised once, so every
-- inserted job is represented here exactly once.
select count(*) as queued_and_sent from sent;
